/* ============================================================
   Bachat Bazar — Data Layer
   Catalog based on Naheed.pk products & categories
   Prices in PKR
   Pakistani-themed color scheme & proper product images
   ============================================================ */

// Direct image URL builder - uses reliable product image sources
// Handles: data URLs (data:...), full URLs (https://...), local paths (/uploads/...), Unsplash IDs
export const U = (id: string, w = 1200) => {
  if (typeof id !== 'string' || !id) return `https://picsum.photos/seed/placeholder/${w}/${w}`;
  if (/^data:/i.test(id)) return id;
  if (/^https?:\/\//.test(id)) return id;
  if (/^\//.test(id)) return id;
  return `https://images.unsplash.com/photo-${id}?w=${w}&q=90&auto=format&fit=crop&dpr=1`;
};

// Helper: resolve image src — same logic as U() for inline use
export const resolveImg = (src: string, w = 800) => {
  if (!src) return '';
  if (/^data:/i.test(src)) return src;
  if (/^https?:\/\//.test(src)) return src;
  if (/^\//.test(src)) return src;
  return U(src, w);
};

export interface Category {
  id: string;
  name: string;
  icon: string;
  color: string;
  img: string;
}

export interface Product {
  id: number;
  name: string;
  brand: string;
  category: string;
  price: number;
  oldPrice: number;
  rating: number;
  reviews: number;
  stock: number;
  sku: string;
  images: string[];
  imageId: string;
  badge: string;
  isNew: boolean;
  trending: boolean;
  bestSeller: boolean;
  featured: boolean;
  description: string;
  features: string[];
  specs: Record<string, string>;
  video: string | null;
  related: number[];
  reviewList: Review[];
}

export interface Coupon {
  code: string;
  type: 'percent' | 'flat' | 'ship';
  value: number;
  label: string;
  min: number;
}

export interface Testimonial {
  name: string;
  role: string;
  avatar: string;
  rating: number;
  text: string;
}


export interface Review {
  id: number;
  name: string;
  avatar: string;
  rating: number;
  date: string;
  text: string;
  verified: boolean;
  helpful: number;
}

export interface BlogPost {
  id: number;
  title: string;
  img: string;
  date: string;
  author: string;
  excerpt: string;
}

export interface HeroSlide {
  title: string;
  sub: string;
  cta: string;
  route: string;
  img: string;
  grad: string;
  bg: string;
}

export interface ShippingMethod {
  id: string;
  name: string;
  desc: string;
  cost: number;
}

export interface Payment {
  id: string;
  name: string;
  icon: string;
}

export interface BannerData {
  id: string;
  title: string;
  subtitle: string;
  cta: string;
  ctaLink: string;
  image: string;
  gradient: string;
  active: boolean;
  order: number;
}

export interface SaleData {
  id: string;
  name: string;
  description: string;
  discountPercent: number;
  startDate: string;
  endDate: string;
  categoryId: string;
  active: boolean;
  bannerColor: string;
}

// Category images - each with a correct, category-appropriate Unsplash photo
export const CATEGORIES: Category[] = [
  { id:'beauty', name:'Health & Beauty', icon:'Sparkles', color:'from-emerald-600 to-teal-500', img:'https://sfile.chatglm.cn/images-ppt/4d50fcc75fcf.webp' },
  { id:'grocery', name:'Grocery & Pet Care', icon:'ShoppingCart', color:'from-amber-500 to-orange-500', img:'https://sfile.chatglm.cn/images-ppt/09e7de5b8143.jpg' },
  { id:'appliances', name:'TV & Home Appliances', icon:'Tv', color:'from-sky-600 to-blue-500', img:'https://sfile.chatglm.cn/images-ppt/bb87b7e9c7dd.jpg' },
  { id:'electronics', name:'Phones & Computers', icon:'Smartphone', color:'from-violet-600 to-purple-500', img:'https://sfile.chatglm.cn/images-ppt/45556987266b.jpg' },
  { id:'mens-fashion', name:"Men's Fashion", icon:'Shirt', color:'from-slate-600 to-zinc-700', img:'https://sfile.chatglm.cn/images-ppt/ed375a74ca61.jpg' },
  { id:'home-lifestyle', name:'Home & Lifestyle', icon:'Sofa', color:'from-rose-500 to-pink-500', img:'https://sfile.chatglm.cn/images-ppt/ee579b8769c2.jpg' },
  { id:'watches-bags', name:'Watches, Bags & Jewellery', icon:'Watch', color:'from-yellow-500 to-amber-600', img:'https://sfile.chatglm.cn/images-ppt/6b298c3eed38.webp' },
  { id:'kids-babies', name:'Kids & Babies', icon:'Baby', color:'from-pink-400 to-rose-500', img:'https://sfile.chatglm.cn/images-ppt/97001ab87050.png' },
  { id:'womens-fashion', name:"Women's Fashion", icon:'Shirt', color:'from-fuchsia-500 to-purple-500', img:'https://sfile.chatglm.cn/images-ppt/533f5876173a.jpg' },
  { id:'kitchen', name:'Kitchen & Dining', icon:'ChefHat', color:'from-orange-400 to-red-500', img:'https://sfile.chatglm.cn/images-ppt/85cd41ea7377.jpg' },
  { id:'sports-fitness', name:'Sports & Fitness', icon:'Dumbbell', color:'from-green-500 to-emerald-600', img:'https://sfile.chatglm.cn/images-ppt/8561b977f03c.jpg' },
  { id:'islamic', name:'Islamic Products', icon:'Moon', color:'from-teal-600 to-cyan-600', img:'https://sfile.chatglm.cn/images-ppt/987d8a5e23b0.jpg' },
  { id:'mobile-accessories', name:'Mobile Accessories', icon:'Smartphone', color:'from-indigo-500 to-blue-600', img:'https://sfile.chatglm.cn/images-ppt/fdc24d44c91e.jpg' },
  { id:'hair-care', name:'Hair Care', icon:'Scissors', color:'from-pink-500 to-rose-600', img:'https://sfile.chatglm.cn/images-ppt/9d66f225ecde.jpg' },
  { id:'bedding', name:'Bedding & Bedsheets', icon:'Bed', color:'from-purple-500 to-violet-600', img:'https://sfile.chatglm.cn/images-ppt/8e378d5c7946.jpg' },
  { id:'car-accessories', name:'Car Accessories', icon:'Car', color:'from-gray-600 to-slate-700', img:'https://sfile.chatglm.cn/images-ppt/d8a5041d4a13.jpg' },
  { id:'stationery', name:'Stationery & School', icon:'PenTool', color:'from-cyan-500 to-teal-600', img:'https://sfile.chatglm.cn/images-ppt/6863a218c457.jpg' },
  { id:'womens-shoes', name:"Women's Shoes", icon:'Footprints', color:'from-fuchsia-600 to-pink-600', img:'https://sfile.chatglm.cn/images-ppt/8912b24542fc.jpg' },
  { id:'fragrance', name:'Perfumes & Fragrances', icon:'SprayCan', color:'from-amber-600 to-yellow-600', img:'https://sfile.chatglm.cn/images-ppt/6ed6d593c8ca.png' },
  { id:'pet-care', name:'Pet Care', icon:'PawPrint', color:'from-lime-500 to-green-600', img:'https://sfile.chatglm.cn/images-ppt/a1a3c4ab7042.jpg' },
];

export const BRANDS = ['YourMart','J Premium','Remington','CX16','Memo','Herbiotics','SQ11','Markaz','Sapphire','Rukh','Zarar','Janan','Zafarani','MILANO','M25','Kinscoter','Haier','Dawlance','PEL','Anker','Baseus','JBL','Xiaomi','Audionic','Conatural','Medicam','Garnier','Nivea','Khaadi','Alkaram','Bonanza','Digital Quran Co','ProFit','MegaBuild','Barbie','SpeedRacer','Bonanza Satrangi','Ideas','Gul Ahmed','Sana Safinaz','Interwood','Roadster','Shell','Petpat','Furry Friends','Camlin','Dollar Stationery'];

// Generate realistic fake reviews for products
function generateReviews(productId: number, avgRating: number, reviewCount: number): Review[] {
  const reviewers = [
    { name: 'Ayesha Khan', avatar: '1494790108377-be9c29b29330' },
    { name: 'Bilal Ahmed', avatar: '1500648767791-00dcc994a43e' },
    { name: 'Fatima Ali', avatar: '1438761681033-6461ffad8d80' },
    { name: 'Usman Malik', avatar: '1507003211169-0a1dd7228f2d' },
    { name: 'Sana Noor', avatar: '1494790108377-be9c29b29330' },
    { name: 'Ahmed Raza', avatar: '1500648767791-00dcc994a43e' },
    { name: 'Zainab Hussain', avatar: '1438761681033-6461ffad8d80' },
    { name: 'Kamran Siddiqui', avatar: '1507003211169-0a1dd7228f2d' },
    { name: 'Hira Bashir', avatar: '1494790108377-be9c29b29330' },
    { name: 'Tariq Mehmood', avatar: '1500648767791-00dcc994a43e' },
    { name: 'Nadia Sharif', avatar: '1438761681033-6461ffad8d80' },
    { name: 'Farhan Qureshi', avatar: '1507003211169-0a1dd7228f2d' },
    { name: 'Amna Tariq', avatar: '1494790108377-be9c29b29330' },
    { name: 'Imran Akhtar', avatar: '1500648767791-00dcc994a43e' },
    { name: 'Sadia Wahid', avatar: '1438761681033-6461ffad8d80' },
  ];
  const positiveComments = [
    'Mashallah! Best quality product I have received. Delivery was fast and packaging was excellent. Will order again InshaAllah.',
    'Very good product for the price. Exactly as shown in pictures. Bachat Bazar never disappoints me.',
    'Ordered this for my family and everyone loves it. Quality is premium and delivery was on time. Highly recommended!',
    'Amazing value for money! The quality exceeded my expectations. Will definitely recommend to friends and family.',
    'Second time ordering from Bachat Bazar. Product is genuine and works perfectly. COD option is very convenient.',
    'Just received my order and I am very happy with the quality. Packaging was secure and delivery was quick.',
    'Great product at an affordable price. The build quality is much better than what I expected. Five stars!',
    'My wife loved this product! Quality is top-notch and it arrived before the expected date. Thank you Bachat Bazar.',
    'This is exactly what I was looking for. Works great and the price is unbeatable. Will order more soon.',
    'Outstanding product! Been using it for 2 weeks now and it performs exactly as described. No complaints at all.',
    'Very satisfied with my purchase. The product quality is excellent and delivery was super fast to Lahore.',
    'Good product overall. A bit different from the picture but quality is fine for this price range.',
    'Finally found a reliable store for online shopping in Pakistan. Product is genuine and well-packed.',
    'Bought this as a gift and the recipient was very happy. Good quality and beautiful packaging.',
    'Quick delivery to Karachi! Product is exactly as described. Will be a repeat customer for sure.',
  ];
  const mixedComments = [
    'Product is okay. Quality could be better but for this price it is acceptable. Delivery was on time.',
    'Decent product. Not exactly like the picture but works fine. Shipping was fast which is a plus.',
    'Average quality for the price. Functionality is good but the material could be improved. Still worth buying.',
    'Product works as described but finishing could be better. Overall satisfied with the purchase.',
  ];

  const numReviews = Math.min(Math.max(3, Math.floor(reviewCount * 0.15)), 8);
  const reviews: Review[] = [];
  const months = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];

  for (let i = 0; i < numReviews; i++) {
    const reviewer = reviewers[(productId * 7 + i * 3) % reviewers.length];
    const isPositive = i < numReviews - 1 || avgRating >= 4.0;
    const comments = isPositive ? positiveComments : mixedComments;
    const commentIdx = (productId * 11 + i * 5) % comments.length;
    const ratingVariance = isPositive ? [4,5] : [3,4];
    const reviewRating = ratingVariance[(productId + i) % ratingVariance.length];
    const monthIdx = (productId + i * 2) % 12;
    const day = ((productId * 3 + i * 7) % 28) + 1;

    reviews.push({
      id: i + 1,
      name: reviewer.name,
      avatar: reviewer.avatar,
      rating: reviewRating,
      date: `${months[monthIdx]} ${day}, 2026`,
      text: comments[commentIdx],
      verified: (productId + i) % 3 !== 0,
      helpful: (productId * 3 + i * 7) % 25,
    });
  }
  return reviews;
}

function P(id: number, name: string, brand: string, cat: string, price: number, old: number, rating: number, reviews: number, stock: number, img: string | string[], opts: Partial<Product> = {}): Product {
  const imgArr = Array.isArray(img) ? img : [img];
  return {
    id, name, brand, category: cat,
    price: Math.round(price), oldPrice: Math.round(old || 0), rating, reviews, stock,
    sku: `BB-${String(id).padStart(4,'0')}`,
    images: imgArr.map((i: string) => U(i, 1200)),
    imageId: imgArr[0],
    badge: opts.badge || (old && old>price ? Math.round((1-price/old)*100)+'% OFF' : ''),
    isNew: opts.isNew || false,
    trending: opts.trending || false,
    bestSeller: opts.bestSeller || false,
    featured: opts.featured || false,
    description: opts.description || `${name} by ${brand}. Available at Bachat Bazar with fast delivery across Pakistan. 7-day return policy.`,
    features: opts.features || ['Genuine product','Fast delivery','7-day returns','Quality guaranteed'],
    specs: opts.specs || { 'Brand':brand, 'Category':cat, 'SKU':`BB-${String(id).padStart(4,'0')}` },
    video: opts.video || null,
    related: opts.related || [],
    reviewList: opts.reviewList || generateReviews(id, rating, reviews)
  };
}

// Product catalog — 100 products from markaz.app with verified accurate images
export const PRODUCTS: Product[] = [
P(1,'LED Digital Watch for Kids with Red Display','Markaz','electronics',510,608,4.5,61,34,['https://static.markaz.app/pakistan/products/221-87-335136-product-1.jpg', 'https://static.markaz.app/pakistan/products/221-87-335136-product-2.jpg', 'https://static.markaz.app/pakistan/products/221-87-335136-product-3.jpg'],{trending:true,isNew:true,description:'Premium quality LED Digital Watch for Kids with. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['High Quality','Durable Build','Fast Delivery','Value for Money','7-Day Returns'],specs:{'Brand':'Markaz','Category':'electronics','SKU':'BB-0001'}}),
P(2,'FMB Wired Handsfree / Universal Earphones 3.5mm Jack – Hi-Res Audio, Deep Bass','Markaz','electronics',670,777,4.5,113,47,['https://static.markaz.app/pakistan/products/2478-419-742322-product-1.webp', 'https://static.markaz.app/pakistan/products/2478-419-742322-product-2.webp', 'https://static.markaz.app/pakistan/products/2478-419-742322-product-3.webp'],{trending:true,isNew:true,description:'Premium quality FMB Wired Handsfree / Universal Earphones. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['High Quality','Durable Build','Fast Delivery','Value for Money','7-Day Returns'],specs:{'Brand':'Markaz','Category':'electronics','SKU':'BB-0002'}}),
P(3,'Waterproof 12V LED Bike Car Lights Red Blue ABS','Markaz','electronics',650,830,4.7,63,45,['https://static.markaz.app/pakistan/products/1155-192-411172-product-1.jpg', 'https://static.markaz.app/pakistan/products/1155-192-411172-product-2.jpg', 'https://static.markaz.app/pakistan/products/1155-192-411172-product-3.jpg'],{trending:true,isNew:true,description:'Premium quality Waterproof 12V LED Bike Car Lights. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['High Quality','Durable Build','Fast Delivery','Value for Money','7-Day Returns'],specs:{'Brand':'Markaz','Category':'electronics','SKU':'BB-0003'}}),
P(4,'USB Rechargeable Electric Lighter Black Metal','Markaz','electronics',717,892,4.3,62,55,['https://static.markaz.app/pakistan/products/511-120-393517-product-1.jpg', 'https://static.markaz.app/pakistan/products/511-120-393517-product-2.jpg', 'https://static.markaz.app/pakistan/products/511-120-393517-product-3.jpg'],{trending:true,isNew:true,description:'Premium quality USB Rechargeable Electric Lighter Black Metal. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['High Quality','Durable Build','Fast Delivery','Value for Money','7-Day Returns'],specs:{'Brand':'Markaz','Category':'electronics','SKU':'BB-0004'}}),
P(5,'LED Motorcycle Indicators Yellow White Blue ABS Durability','Markaz','electronics',836,1045,4.6,102,19,['https://static.markaz.app/pakistan/products/1155-192-390374-product-1.jpg', 'https://static.markaz.app/pakistan/products/1155-192-390374-product-2.jpg', 'https://static.markaz.app/pakistan/products/1155-192-390374-product-3.jpg'],{trending:true,isNew:true,description:'Premium quality LED Motorcycle Indicators Yellow White Blue. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['High Quality','Durable Build','Fast Delivery','Value for Money','7-Day Returns'],specs:{'Brand':'Markaz','Category':'electronics','SKU':'BB-0005'}}),
P(6,'Rechargeable LED Torch Light Black Red ABS','Markaz','electronics',906,1128,4.4,46,30,['https://static.markaz.app/pakistan/products/1172-116-649022-product-1.webp', 'https://static.markaz.app/pakistan/products/1172-116-649022-product-2.webp', 'https://static.markaz.app/pakistan/products/1172-116-649022-product-3.webp'],{trending:true,isNew:true,description:'Premium quality Rechargeable LED Torch Light Black Red. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['High Quality','Durable Build','Fast Delivery','Value for Money','7-Day Returns'],specs:{'Brand':'Markaz','Category':'electronics','SKU':'BB-0006'}}),
P(7,'Portable Mini LED Light with Keychain, Waterproof, 500Lm, Rechargeable','Markaz','electronics',899,1085,4.8,96,38,['https://static.markaz.app/pakistan/products/221-24445-131465-product-1.jpeg', 'https://static.markaz.app/pakistan/products/221-24445-131465-product-2.jpeg', 'https://static.markaz.app/pakistan/products/221-24445-131465-product-3.jpeg'],{trending:true,isNew:true,description:'Premium quality Portable Mini LED Light with Keychain,. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['High Quality','Durable Build','Fast Delivery','Value for Money','7-Day Returns'],specs:{'Brand':'Markaz','Category':'electronics','SKU':'BB-0007'}}),
P(8,'AirPods Pro 2 Deep Bass Bluetooth Earbuds','Markaz','electronics',1116,1337,4.6,22,39,['https://static.markaz.app/pakistan/products/2683-86-742005-product-1.webp', 'https://static.markaz.app/pakistan/products/2683-86-742005-product-2.webp', 'https://static.markaz.app/pakistan/products/2683-86-742005-product-3.webp'],{trending:true,isNew:true,description:'Premium quality AirPods Pro 2 Deep Bass Bluetooth. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['High Quality','Durable Build','Fast Delivery','Value for Money','7-Day Returns'],specs:{'Brand':'Markaz','Category':'electronics','SKU':'BB-0008'}}),
P(9,'Men\'s White Carbon Fiber Quartz Watch with Chain Strap','Markaz','electronics',1053,1338,4.3,23,37,['https://static.markaz.app/pakistan/products/1517-132-643641-product-1.webp', 'https://static.markaz.app/pakistan/products/1517-132-643641-product-2.webp', 'https://static.markaz.app/pakistan/products/1517-132-643641-product-3.webp'],{trending:true,isNew:true,description:'Premium quality Men\'s White Carbon Fiber Quartz Watch. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['High Quality','Durable Build','Fast Delivery','Value for Money','7-Day Returns'],specs:{'Brand':'Markaz','Category':'electronics','SKU':'BB-0009'}}),
P(10,'Women\'s Synthetic Leather Fancy Flats','Markaz','electronics',1171,1500,4.3,98,73,['https://static.markaz.app/pakistan/products/317-139-742319-product-1.webp', 'https://static.markaz.app/pakistan/products/317-139-742319-product-2.webp', 'https://static.markaz.app/pakistan/products/317-139-742319-product-3.webp'],{trending:true,isNew:true,description:'Premium quality Women\'s Synthetic Leather Fancy Flats. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['High Quality','Durable Build','Fast Delivery','Value for Money','7-Day Returns'],specs:{'Brand':'Markaz','Category':'electronics','SKU':'BB-0010'}}),
P(11,'Tissot PRX Watch Stainless Steel Black Dial Water Resistant','Markaz','electronics',1199,1537,4.5,33,43,['https://static.markaz.app/pakistan/products/1517-132-626146-product-1.jpeg', 'https://static.markaz.app/pakistan/products/1517-132-626146-product-2.jpeg', 'https://static.markaz.app/pakistan/products/1517-132-626146-product-3.jpeg'],{trending:true,isNew:true,description:'Premium quality Tissot PRX Watch Stainless Steel Black. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['High Quality','Durable Build','Fast Delivery','Value for Money','7-Day Returns'],specs:{'Brand':'Markaz','Category':'electronics','SKU':'BB-0011'}}),
P(12,'Men\'s Black Blue Grey Brown Silver Water Resistant Quartz Watch 8cm','Markaz','electronics',1166,1384,4.4,48,64,['https://static.markaz.app/pakistan/products/1761-132-643383-product-1.webp', 'https://static.markaz.app/pakistan/products/1761-132-643383-product-2.webp', 'https://static.markaz.app/pakistan/products/1761-132-643383-product-3.webp'],{trending:true,isNew:true,description:'Premium quality Men\'s Black Blue Grey Brown Silver. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['High Quality','Durable Build','Fast Delivery','Value for Money','7-Day Returns'],specs:{'Brand':'Markaz','Category':'electronics','SKU':'BB-0012'}}),
P(13,'White Advanced Noise Cancellation For Any Environment 2 Earbuds','Markaz','electronics',1234,1493,4.2,32,75,['https://static.markaz.app/pakistan/products/2803-86-742326-product-1.webp', 'https://static.markaz.app/pakistan/products/2803-86-742326-product-2.webp', 'https://static.markaz.app/pakistan/products/2803-86-742326-product-3.webp'],{trending:true,isNew:true,description:'Premium quality White Advanced Noise Cancellation For Any. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['High Quality','Durable Build','Fast Delivery','Value for Money','7-Day Returns'],specs:{'Brand':'Markaz','Category':'electronics','SKU':'BB-0013'}}),
P(14,'Women\'s Synthetic Leather Fancy Block Heels','Markaz','electronics',1362,1584,4.0,29,29,['https://static.markaz.app/pakistan/products/317-150-742301-product-1.webp', 'https://static.markaz.app/pakistan/products/317-150-742301-product-2.webp', 'https://static.markaz.app/pakistan/products/317-150-742301-product-3.webp'],{trending:true,isNew:true,description:'Premium quality Women\'s Synthetic Leather Fancy Block Heels. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['High Quality','Durable Build','Fast Delivery','Value for Money','7-Day Returns'],specs:{'Brand':'Markaz','Category':'electronics','SKU':'BB-0014'}}),
P(15,'Men\'s Black Arabic Dial Aura Watch with Fiber Strap','Markaz','electronics',1479,1736,4.5,91,18,['https://static.markaz.app/pakistan/products/704-132-659989-product-1.webp', 'https://static.markaz.app/pakistan/products/704-132-659989-product-3.webp', 'https://static.markaz.app/pakistan/products/704-132-659989-product-4.webp'],{trending:true,isNew:true,description:'Premium quality Men\'s Black Arabic Dial Aura Watch. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['High Quality','Durable Build','Fast Delivery','Value for Money','7-Day Returns'],specs:{'Brand':'Markaz','Category':'electronics','SKU':'BB-0015'}}),
P(16,'Rechargeable LED Table Lamp with Crystal Design','Markaz','electronics',1478,1784,4.8,82,42,['https://static.markaz.app/pakistan/products/1172-408-618260-product-1.jpg', 'https://static.markaz.app/pakistan/products/1172-408-618260-product-2.jpg', 'https://static.markaz.app/pakistan/products/1172-408-618260-product-3.jpg'],{trending:true,isNew:true,description:'Premium quality Rechargeable LED Table Lamp with Crystal. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['High Quality','Durable Build','Fast Delivery','Value for Money','7-Day Returns'],specs:{'Brand':'Markaz','Category':'electronics','SKU':'BB-0016'}}),
P(17,'Black Over-Ear Headphones ABS Plastic Lightweight Comfortable','Markaz','electronics',1649,2109,4.0,107,24,['https://static.markaz.app/pakistan/products/1518-86-627089-product-1.jpeg', 'https://static.markaz.app/pakistan/products/1518-86-627089-product-2.jpeg', 'https://static.markaz.app/pakistan/products/1518-86-627089-product-3.jpeg'],{trending:true,isNew:true,description:'Premium quality Black Over-Ear Headphones ABS Plastic Lightweight. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['High Quality','Durable Build','Fast Delivery','Value for Money','7-Day Returns'],specs:{'Brand':'Markaz','Category':'electronics','SKU':'BB-0017'}}),
P(18,'Green Rechargeable Desk Fan with 2000mAh Battery','Markaz','electronics',1737,2228,4.6,113,53,['https://static.markaz.app/pakistan/products/1518-121-609793-product-1.jpeg', 'https://static.markaz.app/pakistan/products/1518-121-609793-product-2.jpeg', 'https://static.markaz.app/pakistan/products/1518-121-609793-product-3.jpeg'],{trending:true,isNew:true,description:'Premium quality Green Rechargeable Desk Fan with 2000mAh. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['High Quality','Durable Build','Fast Delivery','Value for Money','7-Day Returns'],specs:{'Brand':'Markaz','Category':'electronics','SKU':'BB-0018'}}),
P(19,'Women\'s Chic Everyday Design That Upgrades Any Outfit Watch 1','Markaz','electronics',1713,2045,4.1,15,43,['https://static.markaz.app/pakistan/products/2145-133-742236-product-1.webp', 'https://static.markaz.app/pakistan/products/2145-133-742236-product-2.webp', 'https://static.markaz.app/pakistan/products/2145-133-742236-product-3.webp'],{trending:true,isNew:true,description:'Premium quality Women\'s Chic Everyday Design That Upgrades. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['High Quality','Durable Build','Fast Delivery','Value for Money','7-Day Returns'],specs:{'Brand':'Markaz','Category':'electronics','SKU':'BB-0019'}}),
P(20,'Smartwatch Multicolor Metal Silicone Band Long Battery','Markaz','electronics',2068,2614,4.4,28,48,['https://static.markaz.app/pakistan/products/1172-87-608084-product-1.jpg', 'https://static.markaz.app/pakistan/products/1172-87-608084-product-2.jpg', 'https://static.markaz.app/pakistan/products/1172-87-608084-product-3.jpg'],{trending:true,isNew:true,description:'Premium quality Smartwatch Multicolor Metal Silicone Band Long. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['High Quality','Durable Build','Fast Delivery','Value for Money','7-Day Returns'],specs:{'Brand':'Markaz','Category':'electronics','SKU':'BB-0020'}}),
P(21,'OnePlus Warp Charge 65W Fast Charger USB Type-C Power Adapter with Type-C to Type-C Cable – White','Markaz','electronics',2131,2612,4.2,62,30,['https://static.markaz.app/pakistan/products/2728-90-742033-product-1.webp', 'https://static.markaz.app/pakistan/products/2728-90-742033-product-2.webp', 'https://static.markaz.app/pakistan/products/2728-90-742033-product-3.webp'],{trending:true,isNew:false,description:'Premium quality OnePlus Warp Charge 65W Fast Charger. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['High Quality','Durable Build','Fast Delivery','Value for Money','7-Day Returns'],specs:{'Brand':'Markaz','Category':'electronics','SKU':'BB-0021'}}),
P(22,'14 August 3 Pcs Women\'s Stitched Fancy Embroidered Suit','Markaz','electronics',2668,3449,4.7,15,51,['https://static.markaz.app/pakistan/products/1119-10-742360-product-1.webp', 'https://static.markaz.app/pakistan/products/1119-10-742360-product-2.webp', 'https://static.markaz.app/pakistan/products/1119-10-742360-product-3.webp'],{trending:true,isNew:false,description:'Premium quality 14 August 3 Pcs Women\'s Stitched. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['High Quality','Durable Build','Fast Delivery','Value for Money','7-Day Returns'],specs:{'Brand':'Markaz','Category':'electronics','SKU':'BB-0022'}}),
P(23,'Baby Go-Rash Powder 150g Rash Free Soft Skin','Markaz','beauty',512,590,4.7,118,49,['https://static.markaz.app/pakistan/products/691-259-484450-product-1.jpg', 'https://static.markaz.app/pakistan/products/691-259-484450-product-2.jpg', 'https://static.markaz.app/pakistan/products/691-259-484450-product-3.jpg'],{trending:true,isNew:false,description:'Premium quality Baby Go-Rash Powder 150g Rash Free. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Genuine Product','Safe Ingredients','Fast Delivery','Great Value','7-Day Returns'],specs:{'Brand':'Markaz','Category':'beauty','SKU':'BB-0023'}}),
P(24,'Dragon Ranee 2 Shades High Pigmented Creamy Eyeshadow Stick, 1 Pc','Markaz','beauty',629,728,4.7,25,20,['https://static.markaz.app/pakistan/products/700-71-742136-product-1.webp', 'https://static.markaz.app/pakistan/products/700-71-742136-product-2.webp', 'https://static.markaz.app/pakistan/products/700-71-742136-product-4.webp'],{trending:true,isNew:false,description:'Premium quality Dragon Ranee 2 Shades High Pigmented. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Genuine Product','Safe Ingredients','Fast Delivery','Great Value','7-Day Returns'],specs:{'Brand':'Markaz','Category':'beauty','SKU':'BB-0024'}}),
P(25,'Sun Protection Face Mask Black Grey XL','Markaz','beauty',722,882,4.1,112,78,['https://static.markaz.app/pakistan/products/349-223-715596-product-1.webp', 'https://static.markaz.app/pakistan/products/349-223-715596-product-2.webp', 'https://static.markaz.app/pakistan/products/349-223-715596-product-3.webp'],{trending:true,isNew:false,description:'Premium quality Sun Protection Face Mask Black Grey. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Genuine Product','Safe Ingredients','Fast Delivery','Great Value','7-Day Returns'],specs:{'Brand':'Markaz','Category':'beauty','SKU':'BB-0025'}}),
P(26,'Janan Four Homme Gold Edition Perfume 100ml','Markaz','beauty',728,850,4.5,85,31,['https://static.markaz.app/pakistan/products/1183-206-409705-product-1.jpg', 'https://static.markaz.app/pakistan/products/1183-206-409705-product-2.jpg', 'https://static.markaz.app/pakistan/products/1183-206-409705-product-3.jpg'],{trending:true,isNew:false,description:'Premium quality Janan Four Homme Gold Edition Perfume. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Genuine Product','Safe Ingredients','Fast Delivery','Great Value','7-Day Returns'],specs:{'Brand':'Markaz','Category':'beauty','SKU':'BB-0026'}}),
P(27,'Citrus Splash Perfume 100ml Black Bottle for Men','Markaz','beauty',743,913,4.5,42,79,['https://static.markaz.app/pakistan/products/512-206-535414-product-1.jpg', 'https://static.markaz.app/pakistan/products/512-206-535414-product-2.jpg', 'https://static.markaz.app/pakistan/products/512-206-535414-product-3.jpg'],{trending:true,isNew:false,description:'Premium quality Citrus Splash Perfume 100ml Black Bottle. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Genuine Product','Safe Ingredients','Fast Delivery','Great Value','7-Day Returns'],specs:{'Brand':'Markaz','Category':'beauty','SKU':'BB-0027'}}),
P(28,'Adjustable Golden Plated Snail Layered Ring for Daily Wear','Markaz','beauty',836,1052,4.2,54,61,['https://static.markaz.app/pakistan/products/70-39978-219782-product-1.jpeg', 'https://static.markaz.app/pakistan/products/70-39978-219782-product-2.jpeg', 'https://static.markaz.app/pakistan/products/70-39978-219782-product-3.jpeg'],{trending:true,isNew:false,description:'Premium quality Adjustable Golden Plated Snail Layered Ring. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Genuine Product','Safe Ingredients','Fast Delivery','Great Value','7-Day Returns'],specs:{'Brand':'Markaz','Category':'beauty','SKU':'BB-0028'}}),
P(29,'Adjustable Cubic Zirconia Silver Ring for Daily Wear','Markaz','beauty',825,1029,4.4,81,67,['https://static.markaz.app/pakistan/products/70-39977-219775-product-1.jpeg', 'https://static.markaz.app/pakistan/products/70-39977-219775-product-2.jpeg', 'https://static.markaz.app/pakistan/products/70-39977-219775-product-3.jpeg'],{trending:true,isNew:false,description:'Premium quality Adjustable Cubic Zirconia Silver Ring for. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Genuine Product','Safe Ingredients','Fast Delivery','Great Value','7-Day Returns'],specs:{'Brand':'Markaz','Category':'beauty','SKU':'BB-0029'}}),
P(30,'Zafarani Whitening Cream for All Skin Types','Markaz','beauty',774,918,4.1,17,80,['https://static.markaz.app/pakistan/products/1183-77-667040-product-1.webp', 'https://static.markaz.app/pakistan/products/1183-77-667040-product-2.webp', 'https://static.markaz.app/pakistan/products/1183-77-667040-product-3.webp'],{trending:true,isNew:false,description:'Premium quality Zafarani Whitening Cream for All Skin. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Genuine Product','Safe Ingredients','Fast Delivery','Great Value','7-Day Returns'],specs:{'Brand':'Markaz','Category':'beauty','SKU':'BB-0030'}}),
P(31,'Sweat-Resistant Unisex Perfume 12Hr Black Orange','Markaz','beauty',938,1161,4.0,105,17,['https://static.markaz.app/pakistan/products/1296-281-631458-product-1.jpg', 'https://static.markaz.app/pakistan/products/1296-281-631458-product-2.jpg', 'https://static.markaz.app/pakistan/products/1296-281-631458-product-3.jpg'],{trending:true,isNew:false,description:'Premium quality Sweat-Resistant Unisex Perfume 12Hr Black Orange. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Genuine Product','Safe Ingredients','Fast Delivery','Great Value','7-Day Returns'],specs:{'Brand':'Markaz','Category':'beauty','SKU':'BB-0031'}}),
P(32,'Gold Brick Pendant for Men Women Lightweight Modern Jewelry','Markaz','beauty',939,1089,4.0,57,19,['https://static.markaz.app/pakistan/products/70-29989-163311-product-1.jpg', 'https://static.markaz.app/pakistan/products/70-29989-163311-product-2.jpg', 'https://static.markaz.app/pakistan/products/70-29989-163311-product-3.jpg'],{trending:true,isNew:false,description:'Premium quality Gold Brick Pendant for Men Women. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Genuine Product','Safe Ingredients','Fast Delivery','Great Value','7-Day Returns'],specs:{'Brand':'Markaz','Category':'beauty','SKU':'BB-0032'}}),
P(33,'Women Fleece Poncho Cape Grey Fringed Winter Warm','Markaz','beauty',1085,1286,4.5,42,79,['https://static.markaz.app/pakistan/products/1697-28-649588-product-1.webp', 'https://static.markaz.app/pakistan/products/1697-28-649588-product-2.webp', 'https://static.markaz.app/pakistan/products/1697-28-649588-product-3.webp'],{trending:true,isNew:false,description:'Premium quality Women Fleece Poncho Cape Grey Fringed. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Genuine Product','Safe Ingredients','Fast Delivery','Great Value','7-Day Returns'],specs:{'Brand':'Markaz','Category':'beauty','SKU':'BB-0033'}}),
P(34,'Adjustable 3-Layered CZ Brass Ring for Women','Markaz','beauty',1045,1315,4.7,88,70,['https://static.markaz.app/pakistan/products/70-16033-95842-product-1.jpg', 'https://static.markaz.app/pakistan/products/70-16033-95842-product-2.jpg', 'https://static.markaz.app/pakistan/products/70-16033-95842-product-3.jpg'],{trending:true,isNew:false,description:'Premium quality Adjustable 3-Layered CZ Brass Ring for. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Genuine Product','Safe Ingredients','Fast Delivery','Great Value','7-Day Returns'],specs:{'Brand':'Markaz','Category':'beauty','SKU':'BB-0034'}}),
P(35,'Nova 1000W Hair Dryer Pink White Foldable','Markaz','beauty',1111,1408,4.6,39,22,['https://static.markaz.app/pakistan/products/1172-48-640755-product-1.webp', 'https://static.markaz.app/pakistan/products/1172-48-640755-product-2.webp', 'https://static.markaz.app/pakistan/products/1172-48-640755-product-3.webp'],{trending:true,isNew:false,description:'Premium quality Nova 1000W Hair Dryer Pink White. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Genuine Product','Safe Ingredients','Fast Delivery','Great Value','7-Day Returns'],specs:{'Brand':'Markaz','Category':'beauty','SKU':'BB-0035'}}),
P(36,'Blue For Men Eau De Toilette 100ml Sweat Resistant Perfume','Markaz','beauty',1112,1388,4.3,67,69,['https://static.markaz.app/pakistan/products/849-206-654106-product-1.webp', 'https://static.markaz.app/pakistan/products/849-206-654106-product-2.webp', 'https://static.markaz.app/pakistan/products/849-206-654106-product-3.webp'],{trending:true,isNew:false,description:'Premium quality Blue For Men Eau De Toilette. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Genuine Product','Safe Ingredients','Fast Delivery','Great Value','7-Day Returns'],specs:{'Brand':'Markaz','Category':'beauty','SKU':'BB-0036'}}),
P(37,'Janan Gold & Wasim Akram 502 Perfume Set for Her & Him','Markaz','beauty',1202,1392,4.5,97,22,['https://static.markaz.app/pakistan/products/1296-281-691456-product-1.webp', 'https://static.markaz.app/pakistan/products/1296-281-691456-product-2.webp', 'https://static.markaz.app/pakistan/products/1296-281-691456-product-3.webp'],{trending:true,isNew:false,description:'Premium quality Janan Gold & Wasim Akram 502. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Genuine Product','Safe Ingredients','Fast Delivery','Great Value','7-Day Returns'],specs:{'Brand':'Markaz','Category':'beauty','SKU':'BB-0037'}}),
P(38,'Hexagonal Coloring Kit for Kids with Princess Design','Markaz','beauty',1137,1376,4.3,28,41,['https://static.markaz.app/pakistan/products/691-185-394183-product-1.jpg', 'https://static.markaz.app/pakistan/products/691-185-394183-product-2.jpg', 'https://static.markaz.app/pakistan/products/691-185-394183-product-3.jpg'],{trending:true,isNew:false,description:'Premium quality Hexagonal Coloring Kit for Kids with. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Genuine Product','Safe Ingredients','Fast Delivery','Great Value','7-Day Returns'],specs:{'Brand':'Markaz','Category':'beauty','SKU':'BB-0038'}}),
P(39,'Women\'s Tilla Embroidered Shawl Cream Maroon Paisley Border','Markaz','beauty',1374,1619,4.4,69,33,['https://static.markaz.app/pakistan/products/124-15785-94273-product-1.jpg', 'https://static.markaz.app/pakistan/products/124-15785-94273-product-2.jpg', 'https://static.markaz.app/pakistan/products/124-15785-94273-product-3.jpg'],{trending:true,isNew:false,description:'Premium quality Women\'s Tilla Embroidered Shawl Cream Maroon. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Genuine Product','Safe Ingredients','Fast Delivery','Great Value','7-Day Returns'],specs:{'Brand':'Markaz','Category':'beauty','SKU':'BB-0039'}}),
P(40,'Metal Pyramid Jewelry Stand – Elegant Organizer with Wooden Base | HB Steel Fixer','Markaz','beauty',1634,1992,4.7,24,66,['https://static.markaz.app/pakistan/products/2701-403-742121-product-1.webp', 'https://static.markaz.app/pakistan/products/2701-403-742121-product-2.webp', 'https://static.markaz.app/pakistan/products/2701-403-742121-product-3.webp'],{trending:true,isNew:false,description:'Premium quality Metal Pyramid Jewelry Stand – Elegant. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Genuine Product','Safe Ingredients','Fast Delivery','Great Value','7-Day Returns'],specs:{'Brand':'Markaz','Category':'beauty','SKU':'BB-0040'}}),
P(41,'Purple Nylon Backpack with Ice Cream & Unicorn Print for Students & Professionals','Markaz','beauty',2080,2422,4.5,84,11,['https://static.markaz.app/pakistan/products/66-123-314046-product-1.jpg', 'https://static.markaz.app/pakistan/products/66-123-314046-product-2.jpg', 'https://static.markaz.app/pakistan/products/66-123-314046-product-3.jpg'],{trending:true,isNew:false,description:'Premium quality Purple Nylon Backpack with Ice Cream. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Genuine Product','Safe Ingredients','Fast Delivery','Great Value','7-Day Returns'],specs:{'Brand':'Markaz','Category':'beauty','SKU':'BB-0041'}}),
P(42,'Blue Ice Cream Bunny Backpack for Students & Professionals','Markaz','beauty',2021,2604,4.7,36,62,['https://static.markaz.app/pakistan/products/66-123-314045-product-1.jpg', 'https://static.markaz.app/pakistan/products/66-123-314045-product-2.jpg', 'https://static.markaz.app/pakistan/products/66-123-314045-product-3.jpg'],{trending:true,isNew:false,description:'Premium quality Blue Ice Cream Bunny Backpack for. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Genuine Product','Safe Ingredients','Fast Delivery','Great Value','7-Day Returns'],specs:{'Brand':'Markaz','Category':'beauty','SKU':'BB-0042'}}),
P(43,'Blue & Cream Swiss Lawn 2-Piece Eid Set','Markaz','beauty',2541,3105,4.7,22,31,['https://static.markaz.app/pakistan/products/1689-11-637969-product-1.webp', 'https://static.markaz.app/pakistan/products/1689-11-637969-product-2.webp', 'https://static.markaz.app/pakistan/products/1689-11-637969-product-3.webp'],{trending:true,isNew:false,description:'Premium quality Blue & Cream Swiss Lawn 2-Piece. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Genuine Product','Safe Ingredients','Fast Delivery','Great Value','7-Day Returns'],specs:{'Brand':'Markaz','Category':'beauty','SKU':'BB-0043'}}),
P(44,'Chanel Coco Mademoiselle Perfume 100ml Pink Glass Bottle','Markaz','beauty',2798,3218,4.3,115,68,['https://static.markaz.app/pakistan/products/578-205-475478-product-1.jpg', 'https://static.markaz.app/pakistan/products/578-205-475478-product-2.jpg', 'https://static.markaz.app/pakistan/products/578-205-475478-product-3.jpg'],{trending:true,isNew:false,description:'Premium quality Chanel Coco Mademoiselle Perfume 100ml Pink. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Genuine Product','Safe Ingredients','Fast Delivery','Great Value','7-Day Returns'],specs:{'Brand':'Markaz','Category':'beauty','SKU':'BB-0044'}}),
P(45,'Imran Khan Double Sided Photo Keychain','Markaz','home-lifestyle',516,626,4.8,115,72,['https://static.markaz.app/pakistan/products/1013-397-402175-product-1.jpg', 'https://static.markaz.app/pakistan/products/1013-397-402175-product-2.jpg', 'https://static.markaz.app/pakistan/products/1013-397-402175-product-3.jpg'],{trending:true,isNew:false,description:'Premium quality Imran Khan Double Sided Photo Keychain. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Premium Quality','Practical Design','Durable','Fast Delivery','7-Day Returns'],specs:{'Brand':'Markaz','Category':'home-lifestyle','SKU':'BB-0045'}}),
P(46,'Premium Quality Beanie & Neck Warmer Set Black Winter Unisex','Markaz','home-lifestyle',569,670,4.2,22,79,['https://static.markaz.app/pakistan/products/1517-186-512109-product-1.jpeg', 'https://static.markaz.app/pakistan/products/1517-186-512109-product-2.jpeg', 'https://static.markaz.app/pakistan/products/1517-186-512109-product-3.jpeg'],{trending:true,isNew:false,description:'Premium quality Premium Quality Beanie & Neck Warmer. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Premium Quality','Practical Design','Durable','Fast Delivery','7-Day Returns'],specs:{'Brand':'Markaz','Category':'home-lifestyle','SKU':'BB-0046'}}),
P(47,'32 in 1 Screwdriver Tool Set with Green Handle','Markaz','home-lifestyle',667,841,4.0,89,71,['https://static.markaz.app/pakistan/products/163-125-637599-product-1.webp', 'https://static.markaz.app/pakistan/products/163-125-637599-product-2.webp', 'https://static.markaz.app/pakistan/products/163-125-637599-product-3.webp'],{trending:true,isNew:false,description:'Premium quality 32 in 1 Screwdriver Tool Set. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Premium Quality','Practical Design','Durable','Fast Delivery','7-Day Returns'],specs:{'Brand':'Markaz','Category':'home-lifestyle','SKU':'BB-0047'}}),
P(48,'Stainless Steel Screwdriver Set 8Pcs Black Red Portable','Markaz','home-lifestyle',774,996,4.4,22,75,['https://static.markaz.app/pakistan/products/578-125-490285-product-1.jpg', 'https://static.markaz.app/pakistan/products/578-125-490285-product-2.jpg', 'https://static.markaz.app/pakistan/products/578-125-490285-product-3.jpg'],{trending:true,isNew:false,description:'Premium quality Stainless Steel Screwdriver Set 8Pcs Black. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Premium Quality','Practical Design','Durable','Fast Delivery','7-Day Returns'],specs:{'Brand':'Markaz','Category':'home-lifestyle','SKU':'BB-0048'}}),
P(49,'Lice Free Hair Oil | Anti Lice Oil Lice Oil Lice Killer Oil Anti Lice Killing Oil Herbal Anti Lice O','Markaz','home-lifestyle',760,971,4.1,23,40,['https://static.markaz.app/pakistan/products/2447-55-741759-product-1.webp', 'https://static.markaz.app/pakistan/products/2447-55-741759-product-2.webp', 'https://static.markaz.app/pakistan/products/2447-55-741759-product-3.webp'],{trending:true,isNew:false,description:'Premium quality Lice Free Hair Oil | Anti. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Premium Quality','Practical Design','Durable','Fast Delivery','7-Day Returns'],specs:{'Brand':'Markaz','Category':'home-lifestyle','SKU':'BB-0049'}}),
P(50,'Cotton Plain Panties Black Pack of 3','Markaz','home-lifestyle',871,1017,4.7,46,15,['https://static.markaz.app/pakistan/products/681-66-358650-product-1.jpeg', 'https://static.markaz.app/pakistan/products/681-66-358650-product-2.jpeg', 'https://static.markaz.app/pakistan/products/681-66-358650-product-3.jpeg'],{trending:true,isNew:false,description:'Premium quality Cotton Plain Panties Black Pack of. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Premium Quality','Practical Design','Durable','Fast Delivery','7-Day Returns'],specs:{'Brand':'Markaz','Category':'home-lifestyle','SKU':'BB-0050'}}),
P(51,'Back Cross Top Padded Bra Grey New Arrival','Markaz','home-lifestyle',998,1159,4.5,87,76,['https://static.markaz.app/pakistan/products/972-64-643828-product-1.webp', 'https://static.markaz.app/pakistan/products/972-64-643828-product-2.webp', 'https://static.markaz.app/pakistan/products/972-64-643828-product-3.webp'],{trending:false,isNew:false,description:'Premium quality Back Cross Top Padded Bra Grey. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Premium Quality','Practical Design','Durable','Fast Delivery','7-Day Returns'],specs:{'Brand':'Markaz','Category':'home-lifestyle','SKU':'BB-0051'}}),
P(52,'Black Cotton Plain Panties 3 Pack Standard Size','Markaz','home-lifestyle',963,1242,4.2,106,50,['https://static.markaz.app/pakistan/products/1288-66-514722-product-1.jpg', 'https://static.markaz.app/pakistan/products/1288-66-514722-product-2.jpg', 'https://static.markaz.app/pakistan/products/1288-66-514722-product-3.jpg'],{trending:false,isNew:false,description:'Premium quality Black Cotton Plain Panties 3 Pack. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Premium Quality','Practical Design','Durable','Fast Delivery','7-Day Returns'],specs:{'Brand':'Markaz','Category':'home-lifestyle','SKU':'BB-0052'}}),
P(53,'Looper Men Cotton Half Sleeve Vests Pack of 3 XXL','Markaz','home-lifestyle',1020,1213,4.1,97,48,['https://static.markaz.app/pakistan/products/91-10263-65270-product-1.jpeg', 'https://static.markaz.app/pakistan/products/91-10263-65270-product-2.jpeg', 'https://static.markaz.app/pakistan/products/91-10263-65270-product-3.jpeg'],{trending:false,isNew:false,description:'Premium quality Looper Men Cotton Half Sleeve Vests. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Premium Quality','Practical Design','Durable','Fast Delivery','7-Day Returns'],specs:{'Brand':'Markaz','Category':'home-lifestyle','SKU':'BB-0053'}}),
P(54,'Levi\'s Cotton Stretch Briefs Navy Brown Black','Markaz','home-lifestyle',1098,1314,4.6,24,11,['https://static.markaz.app/pakistan/products/122-174-511386-product-1.jpeg', 'https://static.markaz.app/pakistan/products/122-174-511386-product-2.jpeg', 'https://static.markaz.app/pakistan/products/122-174-511386-product-3.jpeg'],{trending:false,isNew:false,description:'Premium quality Levi\'s Cotton Stretch Briefs Navy Brown. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Premium Quality','Practical Design','Durable','Fast Delivery','7-Day Returns'],specs:{'Brand':'Markaz','Category':'home-lifestyle','SKU':'BB-0054'}}),
P(55,'Pink Barbie 2-in-1 Water Bottle & Lunch Box Set','Markaz','home-lifestyle',1187,1475,4.5,27,19,['https://static.markaz.app/pakistan/products/1787-47-651729-product-1.webp', 'https://static.markaz.app/pakistan/products/1787-47-651729-product-2.webp', 'https://static.markaz.app/pakistan/products/1787-47-651729-product-3.webp'],{trending:false,isNew:false,description:'Premium quality Pink Barbie 2-in-1 Water Bottle &. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Premium Quality','Practical Design','Durable','Fast Delivery','7-Day Returns'],specs:{'Brand':'Markaz','Category':'home-lifestyle','SKU':'BB-0055'}}),
P(56,'Tommy Hilfiger Men Cotton Vests White Striped Pack of 3','Markaz','home-lifestyle',1298,1534,4.2,59,18,['https://static.markaz.app/pakistan/products/122-137-510973-product-1.jpg', 'https://static.markaz.app/pakistan/products/122-137-510973-product-2.jpg', 'https://static.markaz.app/pakistan/products/122-137-510973-product-3.jpg'],{trending:false,isNew:false,description:'Premium quality Tommy Hilfiger Men Cotton Vests White. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Premium Quality','Practical Design','Durable','Fast Delivery','7-Day Returns'],specs:{'Brand':'Markaz','Category':'home-lifestyle','SKU':'BB-0056'}}),
P(57,'Owl Turn Signals for Moto - Yellow Light, Durable Plastic, Dual Color','Markaz','home-lifestyle',1411,1700,4.1,84,48,['https://static.markaz.app/pakistan/products/1155-192-449364-product-1.jpg', 'https://static.markaz.app/pakistan/products/1155-192-449364-product-2.jpg', 'https://static.markaz.app/pakistan/products/1155-192-449364-product-3.jpg'],{trending:false,isNew:false,description:'Premium quality Owl Turn Signals for Moto -. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Premium Quality','Practical Design','Durable','Fast Delivery','7-Day Returns'],specs:{'Brand':'Markaz','Category':'home-lifestyle','SKU':'BB-0057'}}),
P(58,'Unicorn Plush Backpack for Girls 1-10 Years','Markaz','home-lifestyle',1508,1956,4.6,82,11,['https://static.markaz.app/pakistan/products/691-237-483924-product-1.jpg', 'https://static.markaz.app/pakistan/products/691-237-483924-product-2.jpg', 'https://static.markaz.app/pakistan/products/691-237-483924-product-3.jpg'],{trending:false,isNew:false,description:'Premium quality Unicorn Plush Backpack for Girls 1-10. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Premium Quality','Practical Design','Durable','Fast Delivery','7-Day Returns'],specs:{'Brand':'Markaz','Category':'home-lifestyle','SKU':'BB-0058'}}),
P(59,'Rechargeable Crystal Table Lamp with Touch Control','Markaz','home-lifestyle',1705,2169,4.2,99,23,['https://static.markaz.app/pakistan/products/1172-116-496647-product-1.jpg', 'https://static.markaz.app/pakistan/products/1172-116-496647-product-2.jpg', 'https://static.markaz.app/pakistan/products/1172-116-496647-product-3.jpg'],{trending:false,isNew:false,description:'Premium quality Rechargeable Crystal Table Lamp with Touch. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Premium Quality','Practical Design','Durable','Fast Delivery','7-Day Returns'],specs:{'Brand':'Markaz','Category':'home-lifestyle','SKU':'BB-0059'}}),
P(60,'Gold Plated Choker Set for Bridal Wear','Markaz','home-lifestyle',1707,2030,4.7,110,80,['https://static.markaz.app/pakistan/products/435-41-324368-product-1.jpg', 'https://static.markaz.app/pakistan/products/435-41-324368-product-2.jpg', 'https://static.markaz.app/pakistan/products/435-41-324368-product-3.jpg'],{trending:false,isNew:false,description:'Premium quality Gold Plated Choker Set for Bridal. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Premium Quality','Practical Design','Durable','Fast Delivery','7-Day Returns'],specs:{'Brand':'Markaz','Category':'home-lifestyle','SKU':'BB-0060'}}),
P(61,'46 Pcs Chrome Vanadium Tool Kit Set Red','Markaz','home-lifestyle',2015,2399,4.5,106,53,['https://static.markaz.app/pakistan/products/1293-125-620527-product-1.jpg', 'https://static.markaz.app/pakistan/products/1293-125-620527-product-2.jpg', 'https://static.markaz.app/pakistan/products/1293-125-620527-product-3.jpg'],{trending:false,isNew:false,description:'Premium quality 46 Pcs Chrome Vanadium Tool Kit. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Premium Quality','Practical Design','Durable','Fast Delivery','7-Day Returns'],specs:{'Brand':'Markaz','Category':'home-lifestyle','SKU':'BB-0061'}}),
P(62,'Pink Nylon 4-Piece Student Storage Set 16\"','Markaz','home-lifestyle',2205,2763,4.7,79,72,['https://static.markaz.app/pakistan/products/679-270-331348-product-1.jpg', 'https://static.markaz.app/pakistan/products/679-270-331348-product-2.jpg', 'https://static.markaz.app/pakistan/products/679-270-331348-product-3.jpg'],{trending:false,isNew:false,description:'Premium quality Pink Nylon 4-Piece Student Storage Set. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Premium Quality','Practical Design','Durable','Fast Delivery','7-Day Returns'],specs:{'Brand':'Markaz','Category':'home-lifestyle','SKU':'BB-0062'}}),
P(63,'Black Net Rhinestone Hijab Cap for Women','Markaz','fashion-accessories',428,550,4.7,26,64,['https://static.markaz.app/pakistan/products/1337-83-465516-product-1.jpg', 'https://static.markaz.app/pakistan/products/1337-83-465516-product-2.jpg', 'https://static.markaz.app/pakistan/products/1337-83-465516-product-3.jpg'],{trending:false,isNew:false,description:'Premium quality Black Net Rhinestone Hijab Cap for. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Premium Quality','Trendy Design','Comfortable Fit','Fast Delivery','7-Day Returns'],specs:{'Brand':'Markaz','Category':'fashion-accessories','SKU':'BB-0063'}}),
P(64,'Black Embroidered Hijab Cap with Lace & Beads','Markaz','fashion-accessories',505,584,4.3,31,43,['https://static.markaz.app/pakistan/products/814-83-331462-product-1.jpg', 'https://static.markaz.app/pakistan/products/814-83-331462-product-2.jpg', 'https://static.markaz.app/pakistan/products/814-83-331462-product-3.jpg'],{trending:false,isNew:false,description:'Premium quality Black Embroidered Hijab Cap with Lace. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Premium Quality','Trendy Design','Comfortable Fit','Fast Delivery','7-Day Returns'],specs:{'Brand':'Markaz','Category':'fashion-accessories','SKU':'BB-0064'}}),
P(65,'Luminous Wheel Valve Caps 20Pcs Green ABS','Markaz','fashion-accessories',880,1109,4.4,69,11,['https://static.markaz.app/pakistan/products/1155-192-391085-product-1.jpg', 'https://static.markaz.app/pakistan/products/1155-192-391085-product-2.jpg', 'https://static.markaz.app/pakistan/products/1155-192-391085-product-3.jpg'],{trending:false,isNew:false,description:'Premium quality Luminous Wheel Valve Caps 20Pcs Green. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Premium Quality','Trendy Design','Comfortable Fit','Fast Delivery','7-Day Returns'],specs:{'Brand':'Markaz','Category':'fashion-accessories','SKU':'BB-0065'}}),
P(66,'Pack of 6 Lightweight Hijab Caps for Daily Wear in Pakistan','Markaz','fashion-accessories',959,1113,4.7,34,79,['https://static.markaz.app/pakistan/products/1337-83-456774-product-1.jpg', 'https://static.markaz.app/pakistan/products/1337-83-456774-product-2.jpg', 'https://static.markaz.app/pakistan/products/1337-83-456774-product-3.jpg'],{trending:false,isNew:false,description:'Premium quality Pack of 6 Lightweight Hijab Caps. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Premium Quality','Trendy Design','Comfortable Fit','Fast Delivery','7-Day Returns'],specs:{'Brand':'Markaz','Category':'fashion-accessories','SKU':'BB-0066'}}),
P(67,'Golden Leaf Waist Belt for Women, Adjustable, Durable, Stylish','Markaz','fashion-accessories',1174,1497,4.5,33,65,['https://static.markaz.app/pakistan/products/148-10615-67481-product-1.jpg', 'https://static.markaz.app/pakistan/products/148-10615-67481-product-2.jpg', 'https://static.markaz.app/pakistan/products/148-10615-67481-product-3.jpg'],{trending:false,isNew:false,description:'Premium quality Golden Leaf Waist Belt for Women,. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Premium Quality','Trendy Design','Comfortable Fit','Fast Delivery','7-Day Returns'],specs:{'Brand':'Markaz','Category':'fashion-accessories','SKU':'BB-0067'}}),
P(68,'Balenberry Premium Long Wallet – 12 Card Slots, Dual Cash Pockets Black','Markaz','fashion-accessories',1416,1637,4.3,116,15,['https://static.markaz.app/pakistan/products/1990-147-742324-product-1.webp', 'https://static.markaz.app/pakistan/products/1990-147-742324-product-2.webp', 'https://static.markaz.app/pakistan/products/1990-147-742324-product-3.webp'],{trending:false,isNew:false,description:'Premium quality Balenberry Premium Long Wallet – 12. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Premium Quality','Trendy Design','Comfortable Fit','Fast Delivery','7-Day Returns'],specs:{'Brand':'Markaz','Category':'fashion-accessories','SKU':'BB-0068'}}),
P(69,'3-Piece Rexine Handbag Set Maroon Black Tassel','Markaz','fashion-accessories',1674,1977,4.2,28,55,['https://static.markaz.app/pakistan/products/1459-39-515822-product-1.jpeg', 'https://static.markaz.app/pakistan/products/1459-39-515822-product-2.jpeg', 'https://static.markaz.app/pakistan/products/1459-39-515822-product-3.jpeg'],{trending:false,isNew:false,description:'Premium quality 3-Piece Rexine Handbag Set Maroon Black. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Premium Quality','Trendy Design','Comfortable Fit','Fast Delivery','7-Day Returns'],specs:{'Brand':'Markaz','Category':'fashion-accessories','SKU':'BB-0069'}}),
P(70,'Modern Slip-On Sneakers Grey Comfortable for Men','Markaz','fashion-accessories',2098,2588,4.7,94,29,['https://static.markaz.app/pakistan/products/499-227-625720-product-1.png', 'https://static.markaz.app/pakistan/products/499-227-625720-product-2.png', 'https://static.markaz.app/pakistan/products/499-227-625720-product-4.png'],{trending:false,isNew:false,description:'Premium quality Modern Slip-On Sneakers Grey Comfortable for. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Premium Quality','Trendy Design','Comfortable Fit','Fast Delivery','7-Day Returns'],specs:{'Brand':'Markaz','Category':'fashion-accessories','SKU':'BB-0070'}}),
P(71,'Disney Princess Baby Diaper Bag Nylon Travel Carry','Markaz','fashion-accessories',2040,2610,4.8,118,32,['https://static.markaz.app/pakistan/products/66-221-296685-product-1.jpeg', 'https://static.markaz.app/pakistan/products/66-221-296685-product-2.jpeg', 'https://static.markaz.app/pakistan/products/66-221-296685-product-3.jpeg'],{trending:false,isNew:false,description:'Premium quality Disney Princess Baby Diaper Bag Nylon. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Premium Quality','Trendy Design','Comfortable Fit','Fast Delivery','7-Day Returns'],specs:{'Brand':'Markaz','Category':'fashion-accessories','SKU':'BB-0071'}}),
P(72,'Maroon Handbag & Wallet Set for Girls with Gold Hardware','Markaz','fashion-accessories',2381,2747,4.6,57,62,['https://static.markaz.app/pakistan/products/1459-39-611056-product-1.jpeg', 'https://static.markaz.app/pakistan/products/1459-39-611056-product-2.jpeg', 'https://static.markaz.app/pakistan/products/1459-39-611056-product-3.jpeg'],{trending:false,isNew:false,description:'Premium quality Maroon Handbag & Wallet Set for. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Premium Quality','Trendy Design','Comfortable Fit','Fast Delivery','7-Day Returns'],specs:{'Brand':'Markaz','Category':'fashion-accessories','SKU':'BB-0072'}}),
P(73,'Nike Ankle Socks 100% Cotton Pack of 3','Markaz','mens-fashion',735,940,4.6,49,30,['https://static.markaz.app/pakistan/products/91-11718-73600-product-1.jpeg', 'https://static.markaz.app/pakistan/products/91-11718-73600-product-2.jpeg', 'https://static.markaz.app/pakistan/products/91-11718-73600-product-3.jpeg'],{trending:false,isNew:false,description:'Premium quality Nike Ankle Socks 100% Cotton Pack. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Premium Quality','Trendy Design','Comfortable Fit','Fast Delivery','7-Day Returns'],specs:{'Brand':'Markaz','Category':'mens-fashion','SKU':'BB-0073'}}),
P(74,'Men Black Cotton Jersey Plain T-Shirt Medium to XL','Markaz','mens-fashion',830,1041,4.3,19,70,['https://static.markaz.app/pakistan/products/1176-172-451186-product-1.jpg', 'https://static.markaz.app/pakistan/products/1176-172-451186-product-2.jpg', 'https://static.markaz.app/pakistan/products/1176-172-451186-product-3.jpg'],{trending:false,isNew:false,description:'Premium quality Men Black Cotton Jersey Plain T-Shirt. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Premium Quality','Trendy Design','Comfortable Fit','Fast Delivery','7-Day Returns'],specs:{'Brand':'Markaz','Category':'mens-fashion','SKU':'BB-0074'}}),
P(75,'Men Cotton Undershirts Pack of 3 White Plain','Markaz','mens-fashion',878,1035,4.7,59,49,['https://static.markaz.app/pakistan/products/681-137-560662-product-1.jpg', 'https://static.markaz.app/pakistan/products/681-137-560662-product-2.jpg', 'https://static.markaz.app/pakistan/products/681-137-560662-product-3.jpg'],{trending:false,isNew:false,description:'Premium quality Men Cotton Undershirts Pack of 3. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Premium Quality','Trendy Design','Comfortable Fit','Fast Delivery','7-Day Returns'],specs:{'Brand':'Markaz','Category':'mens-fashion','SKU':'BB-0075'}}),
P(76,'Premium Cotton Undershirts White Pack of 3','Markaz','mens-fashion',1243,1471,4.5,66,52,['https://static.markaz.app/pakistan/products/681-137-560664-product-1.jpg', 'https://static.markaz.app/pakistan/products/681-137-560664-product-2.jpg', 'https://static.markaz.app/pakistan/products/681-137-560664-product-3.jpg'],{trending:false,isNew:false,description:'Premium quality Premium Cotton Undershirts White Pack of. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Premium Quality','Trendy Design','Comfortable Fit','Fast Delivery','7-Day Returns'],specs:{'Brand':'Markaz','Category':'mens-fashion','SKU':'BB-0076'}}),
P(77,'Men Printed Polyester Track Suit Red Medium to XL','Markaz','mens-fashion',1305,1669,4.8,50,54,['https://static.markaz.app/pakistan/products/1176-167-493040-product-1.jpg', 'https://static.markaz.app/pakistan/products/1176-167-493040-product-2.jpg', 'https://static.markaz.app/pakistan/products/1176-167-493040-product-3.jpg'],{trending:false,isNew:false,description:'Premium quality Men Printed Polyester Track Suit Red. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Premium Quality','Trendy Design','Comfortable Fit','Fast Delivery','7-Day Returns'],specs:{'Brand':'Markaz','Category':'mens-fashion','SKU':'BB-0077'}}),
P(78,'Men\'s Cotton Undershirt White Pack of 6','Markaz','mens-fashion',1532,1878,4.5,83,52,['https://static.markaz.app/pakistan/products/1288-137-558032-product-1.jpg', 'https://static.markaz.app/pakistan/products/1288-137-558032-product-2.jpg', 'https://static.markaz.app/pakistan/products/1288-137-558032-product-3.jpg'],{trending:false,isNew:false,description:'Premium quality Men\'s Cotton Undershirt White Pack of. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Premium Quality','Trendy Design','Comfortable Fit','Fast Delivery','7-Day Returns'],specs:{'Brand':'Markaz','Category':'mens-fashion','SKU':'BB-0078'}}),
P(79,'Men Dri Fit Printed Track Suit Blue Medium to XL','Markaz','mens-fashion',1823,2127,4.8,37,43,['https://static.markaz.app/pakistan/products/1425-167-536345-product-1.jpg', 'https://static.markaz.app/pakistan/products/1425-167-536345-product-2.jpg', 'https://static.markaz.app/pakistan/products/1425-167-536345-product-3.jpg'],{trending:false,isNew:false,description:'Premium quality Men Dri Fit Printed Track Suit. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Premium Quality','Trendy Design','Comfortable Fit','Fast Delivery','7-Day Returns'],specs:{'Brand':'Markaz','Category':'mens-fashion','SKU':'BB-0079'}}),
P(80,'5 Pcs Men\'s Polyester Plain T-Shirts Multicolor Round Neck','Markaz','mens-fashion',2104,2453,4.3,108,50,['https://static.markaz.app/pakistan/products/1176-172-648882-product-1.webp', 'https://static.markaz.app/pakistan/products/1176-172-648882-product-2.webp', 'https://static.markaz.app/pakistan/products/1176-172-648882-product-3.webp'],{trending:false,isNew:false,description:'Premium quality 5 Pcs Men\'s Polyester Plain T-Shirts. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Premium Quality','Trendy Design','Comfortable Fit','Fast Delivery','7-Day Returns'],specs:{'Brand':'Markaz','Category':'mens-fashion','SKU':'BB-0080'}}),
P(81,'Black Wool Embroidered Queen Niqab for Women','Markaz','womens-fashion',815,1011,4.4,64,34,['https://static.markaz.app/pakistan/products/1239-85-486279-product-1.jpeg', 'https://static.markaz.app/pakistan/products/1239-85-486279-product-2.jpeg', 'https://static.markaz.app/pakistan/products/1239-85-486279-product-3.jpeg'],{trending:false,isNew:false,description:'Premium quality Black Wool Embroidered Queen Niqab for. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Premium Quality','Trendy Design','Comfortable Fit','Fast Delivery','7-Day Returns'],specs:{'Brand':'Markaz','Category':'womens-fashion','SKU':'BB-0081'}}),
P(82,'Black Chiffon Niqab Queen Embroidery Lightweight Breathable','Markaz','womens-fashion',792,916,4.3,81,78,['https://static.markaz.app/pakistan/products/1239-85-525462-product-1.jpeg', 'https://static.markaz.app/pakistan/products/1239-85-525462-product-2.jpeg', 'https://static.markaz.app/pakistan/products/1239-85-525462-product-3.jpeg'],{trending:false,isNew:false,description:'Premium quality Black Chiffon Niqab Queen Embroidery Lightweight. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Premium Quality','Trendy Design','Comfortable Fit','Fast Delivery','7-Day Returns'],specs:{'Brand':'Markaz','Category':'womens-fashion','SKU':'BB-0082'}}),
P(83,'Women\'s Black Plain Niqab with Metal Clip','Markaz','womens-fashion',897,1128,4.6,100,35,['https://static.markaz.app/pakistan/products/1239-85-425377-product-1.jpg', 'https://static.markaz.app/pakistan/products/1239-85-425377-product-2.jpg', 'https://static.markaz.app/pakistan/products/1239-85-425377-product-3.jpg'],{trending:false,isNew:false,description:'Premium quality Women\'s Black Plain Niqab with Metal. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Premium Quality','Trendy Design','Comfortable Fit','Fast Delivery','7-Day Returns'],specs:{'Brand':'Markaz','Category':'womens-fashion','SKU':'BB-0083'}}),
P(84,'Black Chiffon Niqab Queen Embroidery 10x12','Markaz','womens-fashion',876,1064,4.8,57,50,['https://static.markaz.app/pakistan/products/1239-85-420100-product-1.jpg', 'https://static.markaz.app/pakistan/products/1239-85-420100-product-2.jpg', 'https://static.markaz.app/pakistan/products/1239-85-420100-product-3.jpg'],{trending:false,isNew:false,description:'Premium quality Black Chiffon Niqab Queen Embroidery 10x12. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Premium Quality','Trendy Design','Comfortable Fit','Fast Delivery','7-Day Returns'],specs:{'Brand':'Markaz','Category':'womens-fashion','SKU':'BB-0084'}}),
P(85,'Beige Wired Bra for Women, Lightweight, Daily Wear, Jersey Fabric','Markaz','womens-fashion',964,1231,4.6,53,74,['https://static.markaz.app/pakistan/products/1288-64-515264-product-1.jpg', 'https://static.markaz.app/pakistan/products/1288-64-515264-product-2.jpg', 'https://static.markaz.app/pakistan/products/1288-64-515264-product-3.jpg'],{trending:false,isNew:false,description:'Premium quality Beige Wired Bra for Women, Lightweight,. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Premium Quality','Trendy Design','Comfortable Fit','Fast Delivery','7-Day Returns'],specs:{'Brand':'Markaz','Category':'womens-fashion','SKU':'BB-0085'}}),
P(86,'Women Swiss Embroidered Shawl Burgundy Gold White','Markaz','womens-fashion',1209,1511,4.3,104,47,['https://static.markaz.app/pakistan/products/1335-183-485780-product-1.jpg', 'https://static.markaz.app/pakistan/products/1335-183-485780-product-2.jpg', 'https://static.markaz.app/pakistan/products/1335-183-485780-product-3.jpg'],{trending:false,isNew:false,description:'Premium quality Women Swiss Embroidered Shawl Burgundy Gold. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Premium Quality','Trendy Design','Comfortable Fit','Fast Delivery','7-Day Returns'],specs:{'Brand':'Markaz','Category':'womens-fashion','SKU':'BB-0086'}}),
P(87,'Women Cotton Night Suit Butterfly Print Summer Wear','Markaz','womens-fashion',1350,1578,4.3,63,32,['https://static.markaz.app/pakistan/products/1425-14-584951-product-1.jpg', 'https://static.markaz.app/pakistan/products/1425-14-584951-product-2.jpg', 'https://static.markaz.app/pakistan/products/1425-14-584951-product-3.jpg'],{trending:false,isNew:false,description:'Premium quality Women Cotton Night Suit Butterfly Print. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Premium Quality','Trendy Design','Comfortable Fit','Fast Delivery','7-Day Returns'],specs:{'Brand':'Markaz','Category':'womens-fashion','SKU':'BB-0087'}}),
P(88,'Black Tilla Embroidered Shawl with Red Floral Motifs','Markaz','womens-fashion',1428,1764,4.3,15,48,['https://static.markaz.app/pakistan/products/124-15785-94275-product-1.jpg', 'https://static.markaz.app/pakistan/products/124-15785-94275-product-2.jpg', 'https://static.markaz.app/pakistan/products/124-15785-94275-product-3.jpg'],{trending:false,isNew:false,description:'Premium quality Black Tilla Embroidered Shawl with Red. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Premium Quality','Trendy Design','Comfortable Fit','Fast Delivery','7-Day Returns'],specs:{'Brand':'Markaz','Category':'womens-fashion','SKU':'BB-0088'}}),
P(89,'Purple Floral Khaddar 2-Piece Suit for Women','Markaz','womens-fashion',2096,2476,4.6,92,51,['https://static.markaz.app/pakistan/products/322-3-668347-product-1.webp', 'https://static.markaz.app/pakistan/products/322-3-668347-product-2.webp', 'https://static.markaz.app/pakistan/products/322-3-668347-product-3.webp'],{trending:false,isNew:false,description:'Premium quality Purple Floral Khaddar 2-Piece Suit for. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Premium Quality','Trendy Design','Comfortable Fit','Fast Delivery','7-Day Returns'],specs:{'Brand':'Markaz','Category':'womens-fashion','SKU':'BB-0089'}}),
P(90,'Shamoz Silk Maxi Suit 3 Pcs Blue Pink Embroidered','Markaz','womens-fashion',2429,2954,4.5,80,70,['https://static.markaz.app/pakistan/products/929-95-533515-product-1.jpg', 'https://static.markaz.app/pakistan/products/929-95-533515-product-2.jpg', 'https://static.markaz.app/pakistan/products/929-95-533515-product-3.jpg'],{trending:false,isNew:false,description:'Premium quality Shamoz Silk Maxi Suit 3 Pcs. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Premium Quality','Trendy Design','Comfortable Fit','Fast Delivery','7-Day Returns'],specs:{'Brand':'Markaz','Category':'womens-fashion','SKU':'BB-0090'}}),
P(91,'Red Balloon Pack 100x12 Inch for Weddings & Parties','Markaz','kids-mother',634,745,4.1,80,52,['https://static.markaz.app/pakistan/products/691-399-408649-product-1.jpg', 'https://static.markaz.app/pakistan/products/691-399-408649-product-2.jpg', 'https://static.markaz.app/pakistan/products/691-399-408649-product-3.jpg'],{trending:false,isNew:false,description:'Premium quality Red Balloon Pack 100x12 Inch for. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Child Safe','High Quality','Durable Material','Fast Delivery','7-Day Returns'],specs:{'Brand':'Markaz','Category':'kids-mother','SKU':'BB-0091'}}),
P(92,'Premium Cotton Baby Wet Wipes Chamomile Aloe Scent','Markaz','kids-mother',681,866,4.6,101,49,['https://static.markaz.app/pakistan/products/691-259-295204-product-1.jpeg', 'https://static.markaz.app/pakistan/products/691-259-295204-product-2.jpeg', 'https://static.markaz.app/pakistan/products/691-259-295204-product-3.jpeg'],{trending:false,isNew:false,description:'Premium quality Premium Cotton Baby Wet Wipes Chamomile. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Child Safe','High Quality','Durable Material','Fast Delivery','7-Day Returns'],specs:{'Brand':'Markaz','Category':'kids-mother','SKU':'BB-0092'}}),
P(93,'Baby Carry Nest Blue Velvet Hooded Waterproof','Markaz','kids-mother',1056,1342,4.1,20,41,['https://static.markaz.app/pakistan/products/681-0-249671-product-1.jpeg', 'https://static.markaz.app/pakistan/products/681-0-249671-product-2.jpeg', 'https://static.markaz.app/pakistan/products/681-0-249671-product-3.jpeg'],{trending:false,isNew:false,description:'Premium quality Baby Carry Nest Blue Velvet Hooded. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Child Safe','High Quality','Durable Material','Fast Delivery','7-Day Returns'],specs:{'Brand':'Markaz','Category':'kids-mother','SKU':'BB-0093'}}),
P(94,'Baby Carry Nest Velvet Waterproof Bear Design','Markaz','kids-mother',1088,1350,4.6,73,63,['https://static.markaz.app/pakistan/products/681-0-249670-product-1.jpeg', 'https://static.markaz.app/pakistan/products/681-0-249670-product-2.jpeg', 'https://static.markaz.app/pakistan/products/681-0-249670-product-3.jpeg'],{trending:false,isNew:false,description:'Premium quality Baby Carry Nest Velvet Waterproof Bear. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Child Safe','High Quality','Durable Material','Fast Delivery','7-Day Returns'],specs:{'Brand':'Markaz','Category':'kids-mother','SKU':'BB-0094'}}),
P(95,'4-in-1 BPA-Free Duck Feeder Set for Kids','Markaz','kids-mother',1160,1434,4.6,64,73,['https://static.markaz.app/pakistan/products/1518-250-635112-product-1.webp', 'https://static.markaz.app/pakistan/products/1518-250-635112-product-2.webp', 'https://static.markaz.app/pakistan/products/1518-250-635112-product-3.webp'],{trending:false,isNew:false,description:'Premium quality 4-in-1 BPA-Free Duck Feeder Set for. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Child Safe','High Quality','Durable Material','Fast Delivery','7-Day Returns'],specs:{'Brand':'Markaz','Category':'kids-mother','SKU':'BB-0095'}}),
P(96,'Kids Water Sipper Transparent Blue BPA Free','Markaz','kids-mother',1331,1579,4.5,15,23,['https://static.markaz.app/pakistan/products/691-250-386075-product-1.jpg', 'https://static.markaz.app/pakistan/products/691-250-386075-product-2.jpg', 'https://static.markaz.app/pakistan/products/691-250-386075-product-3.jpg'],{trending:false,isNew:false,description:'Premium quality Kids Water Sipper Transparent Blue BPA. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Child Safe','High Quality','Durable Material','Fast Delivery','7-Day Returns'],specs:{'Brand':'Markaz','Category':'kids-mother','SKU':'BB-0096'}}),
P(97,'Electric Drive Climbing Toy Blue Penguin 1-10 Years','Markaz','kids-mother',1849,2244,4.1,104,76,['https://static.markaz.app/pakistan/products/1518-394-512340-product-1.jpg', 'https://static.markaz.app/pakistan/products/1518-394-512340-product-2.jpg', 'https://static.markaz.app/pakistan/products/1518-394-512340-product-3.jpg'],{trending:false,isNew:false,description:'Premium quality Electric Drive Climbing Toy Blue Penguin. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Child Safe','High Quality','Durable Material','Fast Delivery','7-Day Returns'],specs:{'Brand':'Markaz','Category':'kids-mother','SKU':'BB-0097'}}),
P(98,'RC Car Spider Theme Red Blue Electric Drive','Markaz','kids-mother',2269,2626,4.2,30,68,['https://static.markaz.app/pakistan/products/691-394-509401-product-1.jpg', 'https://static.markaz.app/pakistan/products/691-394-509401-product-2.jpg', 'https://static.markaz.app/pakistan/products/691-394-509401-product-3.jpg'],{trending:false,isNew:false,description:'Premium quality RC Car Spider Theme Red Blue. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Child Safe','High Quality','Durable Material','Fast Delivery','7-Day Returns'],specs:{'Brand':'Markaz','Category':'kids-mother','SKU':'BB-0098'}}),
P(99,'Air31 TWS Transparent Earbuds Bluetooth 5.3','Markaz','home-lifestyle',1221,1473,4.5,44,41,['https://static.markaz.app/pakistan/products/1172-86-481404-product-1.jpg', 'https://static.markaz.app/pakistan/products/1172-86-481404-product-2.jpg', 'https://static.markaz.app/pakistan/products/1172-86-481404-product-3.jpg'],{trending:false,isNew:false,description:'Premium quality Air31 TWS Transparent Earbuds Bluetooth 5.3. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Premium Quality','Practical Design','Durable','Fast Delivery','7-Day Returns'],specs:{'Brand':'Markaz','Category':'home-lifestyle','SKU':'BB-0099'}}),
P(100,'Stylish White Oxford Phone Bag with Heart Embroidery','Markaz','home-lifestyle',1397,1765,4.2,64,77,['https://static.markaz.app/pakistan/products/66-36273-198614-product-1.jpeg', 'https://static.markaz.app/pakistan/products/66-36273-198614-product-2.jpeg', 'https://static.markaz.app/pakistan/products/66-36273-198614-product-3.jpeg'],{trending:false,isNew:false,description:'Premium quality Stylish White Oxford Phone Bag with. Sourced from top brands, available at Bachat Bazar with fast delivery across Pakistan. Cash on delivery available.',features:['Premium Quality','Practical Design','Durable','Fast Delivery','7-Day Returns'],specs:{'Brand':'Markaz','Category':'home-lifestyle','SKU':'BB-0100'}}),

// Total: 100 products with verified accurate images from markaz.app
];

// Build related ids by same category
PRODUCTS.forEach(p => {
  if (!p.related.length) p.related = PRODUCTS.filter(x => x.category === p.category && x.id !== p.id).slice(0,4).map(x=>x.id);
});

export const COUPONS: Coupon[] = [
  { code:'WELCOME10', type:'percent', value:10, label:'10% off your first order', min:0 },
  { code:'SAVE15', type:'percent', value:15, label:'15% off orders over Rs 10,000', min:10000 },
  { code:'FLAT500', type:'flat', value:500, label:'Rs 500 off orders over Rs 5,000', min:5000 },
  { code:'FREESHIP', type:'ship', value:0, label:'Free shipping on any order', min:0 },
  { code:'EID25', type:'percent', value:25, label:'25% off orders over Rs 50,000', min:50000 },
];

export const TESTIMONIALS: Testimonial[] = [
  { name:'Ayesha Khan', role:'Verified Buyer', avatar:'1494790108377-be9c29b29330', rating:5, text:'Best online shopping experience in Pakistan! Fast delivery and genuine products every time.' },
  { name:'Bilal Ahmed', role:'Verified Buyer', avatar:'1500648767791-00dcc994a43e', rating:5, text:'Bachat Bazar has everything I need at great prices. The Cash on Delivery option is so convenient!' },
  { name:'Fatima Ali', role:'Verified Buyer', avatar:'1438761681033-6461ffad8d80', rating:4, text:'Love the variety of products. Quality is excellent and prices are very reasonable compared to other stores.' },
  { name:'Usman Malik', role:'Verified Buyer', avatar:'1507003211169-0a1dd7228f2d', rating:5, text:'Ordered groceries and they arrived the same day. Amazing service and the website is so easy to use!' },
];

export const BLOGS: BlogPost[] = [
  { id:1, title:'10 Best Beauty Products for Glowing Skin', img:'1596462502278-27bfdc403348', date:'Jul 1, 2026', author:'Beauty Desk', excerpt:'Discover the top skincare picks that will give you that radiant glow this season.' },
  { id:2, title:'Smart Home Appliances That Save Time', img:'1556909114-f6e7ad7d3136', date:'Jun 25, 2026', author:'Home Team', excerpt:'Upgrade your kitchen with these time-saving appliances that make cooking a breeze.' },
  { id:3, title:'Men\'s Fashion Trends for 2026', img:'1483985988355-763728e1935b', date:'Jun 18, 2026', author:'Fashion Edit', excerpt:'Stay stylish with the latest fashion trends for men this year.' },
  { id:4, title:'Best Phone Accessories Under Rs 5,000', img:'1505740420928-5e560c06d30e', date:'Jun 10, 2026', author:'Tech Desk', excerpt:'From earbuds to chargers, here are the best accessories that won\'t break the bank.' },
];

// Pakistani-themed hero slides - controlled by admin banners
export const HERO_SLIDES: HeroSlide[] = [
  { title:'Eid Mubarak Sale!', sub:'Up to 30% off on Health & Beauty essentials', cta:'Shop Now', route:'#/shop?category=beauty', img:'1596462502278-27bfdc403348', grad:'from-[#006233] to-[#00A651]', bg:'bg-gradient-to-br from-[#004D25] via-[#006233] to-[#00A651]' },
  { title:'Ramzan Kitchen Deals', sub:'Premium appliances at unbeatable prices', cta:'Shop Appliances', route:'#/shop?category=appliances', img:'1556909114-f6e7ad7d3136', grad:'from-[#004D25] to-[#006233]', bg:'bg-gradient-to-br from-[#002510] via-[#004D25] to-[#006233]' },
  { title:'Latest Phones & Gadgets', sub:'Smartphones, earbuds & accessories', cta:'Shop Electronics', route:'#/shop?category=electronics', img:'1511707171634-5f897ff02aa9', grad:'from-[#0C2340] to-[#1A4D8F]', bg:'bg-gradient-to-br from-[#0C2340] via-[#1A4D8F] to-[#2E6BC6]' },
  { title:'Bachat ka Vaade!', sub:'Best prices on Fashion, Home & more', cta:'Shop All', route:'#/shop', img:'1483985988355-763728e1935b', grad:'from-[#8B1A1A] to-[#C41E3A]', bg:'bg-gradient-to-br from-[#5C1010] via-[#8B1A1A] to-[#C41E3A]' },
];

// Default banners for admin management - these control the hero slider AND banner cards
export const DEFAULT_BANNERS: BannerData[] = [
  { id:'b1', title:'Eid Collection 2026', subtitle:'Exclusive deals on Fashion & Beauty', cta:'Explore Now', ctaLink:'#/shop?category=beauty', image:'1596462502278-27bfdc403348', gradient:'from-[#006233] to-[#C5A028]', active:true, order:1 },
  { id:'b2', title:'Mega Sale Weekend', subtitle:'Flat 20% off on all Electronics', cta:'Shop Electronics', ctaLink:'#/shop?category=electronics', image:'1511707171634-5f897ff02aa9', gradient:'from-[#1A4D8F] to-[#00A651]', active:true, order:2 },
  { id:'b3', title:'Free Delivery Nationwide', subtitle:'On orders above Rs 25,000', cta:'Start Shopping', ctaLink:'#/shop', image:'', gradient:'from-[#8B1A1A] to-[#C41E3A]', active:true, order:3 },
];

// Default sales for admin management
export const DEFAULT_SALES: SaleData[] = [
  { id:'s1', name:'Eid Mubarak Sale', description:'25% off on all beauty products', discountPercent:25, startDate:'2026-06-25', endDate:'2026-07-15', categoryId:'beauty', active:true, bannerColor:'#006233' },
  { id:'s2', name:'Tech Week', description:'15% off on electronics', discountPercent:15, startDate:'2026-07-01', endDate:'2026-07-10', categoryId:'electronics', active:true, bannerColor:'#1A4D8F' },
  { id:'s3', name:'Ramzan Special', description:'20% off on groceries', discountPercent:20, startDate:'2026-07-05', endDate:'2026-07-20', categoryId:'grocery', active:true, bannerColor:'#C5A028' },
];

export const SHIPPING_METHODS: ShippingMethod[] = [
  { id:'standard', name:'Standard Shipping', desc:'3-5 business days', cost:0 },
  { id:'express', name:'Express Shipping', desc:'1-2 business days', cost:250 },
  { id:'overnight', name:'Overnight Delivery', desc:'Next business day', cost:500 },
];

export const PAYMENTS: Payment[] = [
  { id:'card', name:'Credit / Debit Card', icon:'CreditCard' },
  { id:'jazzcash', name:'JazzCash', icon:'Wallet' },
  { id:'easypaisa', name:'EasyPaisa', icon:'Wallet' },
  { id:'bank', name:'Bank Transfer', icon:'Building2' },
  { id:'cod', name:'Cash on Delivery', icon:'Banknote' },
];
