#!/usr/bin/env python3
"""
Update 2: Add 50+ unique trending low-cost Markaz/YourMart products
and increase existing prices by varied amounts (50-150 Rs based on price tier)
"""

import re, random

with open('src/lib/data.ts', 'r') as f:
    content = f.read()

# ════════════════════════════════════════════════════════════════
# 1. INCREASE EXISTING PRICES BY VARIED AMOUNTS (50-150 Rs)
# ════════════════════════════════════════════════════════════════
# Logic: 
#   Under Rs 500 → +50 Rs
#   Rs 500-1500 → +75 Rs
#   Rs 1500-3000 → +100 Rs
#   Rs 3000-6000 → +125 Rs
#   Rs 6000+ → +150 Rs

def increase_price_varied(match):
    prefix = match.group(1)
    price = int(match.group(2))
    old_price = int(match.group(3))
    
    if price <= 500:
        inc = 50
    elif price <= 1500:
        inc = 75
    elif price <= 3000:
        inc = 100
    elif price <= 6000:
        inc = 125
    else:
        inc = 150
    
    return f"{prefix}{price + inc},{old_price + inc},"

pattern = r"(P\(\d+,'[^']+','[^']*','[^']+',)(\d+),(\d+),"
new_content = re.sub(pattern, increase_price_varied, content)

changes = len(re.findall(pattern, content))
print(f"✅ Price increases applied to {changes} products (varied: 50-150 Rs)")

content = new_content

# ════════════════════════════════════════════════════════════════
# 2. ADD 50+ UNIQUE TRENDING LOW-COST PRODUCTS
# ════════════════════════════════════════════════════════════════

new_products = """
  // ══════════ More Markaz Trending — Unique & Interesting Low-Cost ══════════

  // ---- Smart Gadgets & Novelty (YourMart) ----
  P(193,'Mini Projector Portable 1080P Home Cinema','YourMart','electronics',3750,4500,4.5,68,22,'1504149601548-f22d1f8a388e',{trending:true,isNew:true,description:'Compact mini projector with 1080P support for home cinema experience. Connect via HDMI or WiFi to phone, laptop, or gaming console. Built-in speaker with 3.5mm audio jack. 100-inch projection size perfect for bedroom movie nights. Lightweight and portable for outdoor screenings.',features:['1080P resolution','WiFi + HDMI connect','Built-in speaker','100-inch projection','Portable design'],specs:{'Brand':'YourMart','Type':'Mini Projector','Resolution':'1080P','Connectivity':'WiFi + HDMI','Screen Size':'Up to 100 inch','Speaker':'Built-in'}}),
  P(194,'Smart LED Bulb WiFi RGB 9W Alexa & Google Home','YourMart','home-lifestyle',649,800,4.4,92,45,'1555041469-a586c61ea9bc',{trending:true,bestSeller:true,description:'Smart WiFi LED bulb with 16 million RGB colors. Works with Alexa and Google Home for voice control. 9W energy-efficient with dimmable brightness. Schedule on/off times through the app. Group multiple bulbs for whole-room control. No hub required — connects directly to WiFi.',features:['16M RGB colors','Voice control','9W energy saving','App scheduling','No hub needed'],specs:{'Brand':'YourMart','Type':'Smart Bulb','Power':'9W','Colors':'16 million','Compatibility':'Alexa/Google','Connection':'WiFi direct'}}),
  P(195,'Wireless Doorbell Waterproof 300m Range 38 Chimes','YourMart','home-lifestyle',749,900,4.3,55,38,'1555041469-a586c61ea9bc',{description:'Wireless doorbell with 300m long range and 38 chime melodies. Waterproof transmitter rated IP55 for outdoor use. Plug-in receiver with LED flash indicator. 5 volume levels from mute to loud. Easy installation — no wiring needed. Memory function remembers last setting after power outage.',features:['300m range','38 melodies','IP55 waterproof','LED flash indicator','5 volume levels'],specs:{'Brand':'YourMart','Type':'Wireless Doorbell','Range':'300m','Chimes':'38','Waterproof':'IP55','Power':'Transmitter: 12V 23A / Receiver: Plug-in'}}),
  P(196,'Digital Thermo-Hygrometer Indoor Temperature Humidity','YourMart','home-lifestyle',475,600,4.5,78,55,'1555041469-a586c61ea9bc',{bestSeller:true,description:'Digital thermo-hygrometer for monitoring indoor temperature and humidity. Large LCD display with clear readings. Temperature range -10°C to 50°C with 0.1°C accuracy. Humidity range 10%-99% with 1% accuracy. Tabletop or wall-mount design. Low battery indicator. Perfect for baby room and store room monitoring.',features:['Large LCD display','0.1°C accuracy','Tabletop + wall mount','Low battery indicator','Indoor use'],specs:{'Brand':'YourMart','Type':'Thermo-Hygrometer','Temp Range':'-10 to 50°C','Humidity':'10-99%','Accuracy':'0.1°C / 1%','Power':'AAA battery'}}),
  P(197,'USB Desk Fan Silent 3-Speed 5 Blade Foldable','YourMart','home-lifestyle',399,500,4.4,105,70,'1555041469-a586c61ea9bc',{trending:true,bestSeller:true,description:'Ultra-quiet USB desk fan with 3 speed settings and 5 blades. Foldable design for easy storage and travel. USB powered — works with laptop, power bank, or adapter. 360° adjustable tilt angle. Low noise at just 25dB for office and study. Strong airflow despite compact size.',features:['3 speed settings','5-blade design','USB powered','25dB ultra-quiet','Foldable portable'],specs:{'Brand':'YourMart','Type':'USB Fan','Speeds':'3','Blades':'5','Noise':'25dB','Power':'USB 5V','Angle':'360° tilt'}}),

  // ---- Trending Beauty & Skincare (Markaz) ----
  P(198,'Vitamin C Face Wash Brightening 150ml with Aloe Vera','Markaz','beauty',375,500,4.5,112,65,'1596462502278-27bfdc403348',{trending:true,bestSeller:true,description:'Brightening vitamin C face wash enriched with aloe vera for daily cleansing. Removes dirt, oil, and impurities while brightening skin tone. Gentle formula suitable for all skin types including sensitive. 150ml tube with flip cap for easy dispensing. Visible results in 2 weeks of regular use.',features:['Vitamin C enriched','Aloe vera soothing','Brightening effect','All skin types','150ml flip tube'],specs:{'Brand':'Markaz','Type':'Face Wash','Volume':'150ml','Key Ingredient':'Vitamin C + Aloe','Skin Type':'All','Result':'Brightening in 2 weeks'}}),
  P(199,'Blackhead Remover Mask Activated Charcoal 60ml','Markaz','beauty',349,450,4.3,88,55,'1596462502278-27bfdc403348',{trending:true,description:'Activated charcoal blackhead remover mask for deep pore cleansing. Peels off to remove blackheads, whiteheads, and dead skin. 60ml tube for 15-20 applications. Works best on nose, chin, and forehead. Minimizes pore appearance with regular use. Easy peel-off formula without pain.',features:['Activated charcoal','Deep pore cleanse','Peel-off formula','15-20 uses','Pore minimizing'],specs:{'Brand':'Markaz','Type':'Face Mask','Volume':'60ml','Key Ingredient':'Activated Charcoal','Use':'Nose/Chin/Forehead','Applications':'15-20'}}),
  P(200,'Under Eye Cream Dark Circles Puffiness 30ml Caffeine','Markaz','beauty',425,550,4.6,62,30,'1596462502278-27bfdc403348',{isNew:true,description:'Caffeine-infused under eye cream for dark circles and puffiness. 30ml airless pump bottle for hygienic application. Caffeine constricts blood vessels to reduce dark circles. Hyaluronic acid hydrates and plumps fine lines. Cooling metal applicator soothes tired eyes. Results visible in 3-4 weeks of twice-daily use.',features:['Caffeine formula','Hyaluronic acid','Metal applicator','Dark circle reduction','30ml airless pump'],specs:{'Brand':'Markaz','Type':'Eye Cream','Volume':'30ml','Key Ingredient':'Caffeine + HA','Use':'Twice daily','Result':'3-4 weeks'}}),
  P(201,'Retinol Night Cream Anti-Aging 50ml Collagen Boost','Markaz','beauty',575,700,4.4,45,20,'1596462502278-27bfdc403348',{description:'Retinol night cream with collagen-boosting formula for anti-aging. 50ml jar with protective inner seal. Reduces fine lines and wrinkles while you sleep. Retinol accelerates cell turnover for youthful skin. Vitamin E and shea butter moisturize deeply. Use every other night for first 2 weeks then nightly.',features:['Retinol anti-aging','Collagen boost','Night treatment','Vitamin E enriched','50ml jar'],specs:{'Brand':'Markaz','Type':'Night Cream','Volume':'50ml','Key Ingredient':'Retinol','Use':'Nightly','Result':'Fine line reduction'}}),
  P(202,'Lip Tint Set 6 Colors Long-Lasting Waterproof','Markaz','beauty',399,500,4.5,95,50,'1596462502278-27bfdc403348',{trending:true,bestSeller:true,description:'6-color lip tint set in beautiful everyday shades. Long-lasting waterproof formula stays for 8+ hours. Lightweight matte finish without drying lips. Natural tint builds from sheer to bold. Compact palette perfect for purse. Shades: Nude, Rose, Berry, Coral, Mauve, and Red.',features:['6 lip tints','8+ hour lasting','Waterproof','Matte finish','Buildable color'],specs:{'Brand':'Markaz','Type':'Lip Tint Set','Colors':'6','Finish':'Matte','Duration':'8+ hours','Shades':'Nude/Rose/Berry/Coral/Mauve/Red'}}),

  // ---- Kitchen Gadgets & Tools (YourMart) ----
  P(203,'Electric Garlic Chopper USB Rechargeable 250ml','YourMart','kitchen',875,1050,4.6,72,30,'1556909114-f6e7ad7d3136',{trending:true,isNew:true,description:'Electric garlic chopper with USB rechargeable battery. 250ml BPA-free bowl chops garlic, onion, and herbs in seconds. One-touch operation — just press and chop. 3 stainless steel blades for even results. Compact design saves kitchen space. Easy to clean — just rinse under water.',features:['USB rechargeable','250ml capacity','One-touch chop','3 SS blades','BPA-free bowl'],specs:{'Brand':'YourMart','Type':'Electric Chopper','Capacity':'250ml','Blades':'3 stainless steel','Power':'USB rechargeable','Material':'BPA-free'}}),
  P(204,'Vegetable Cutter Mandoline Slicer 5-in-1 Adjustable','YourMart','kitchen',649,800,4.4,58,35,'1556909114-f6e7ad7d3136',{description:'5-in-1 mandoline slicer with adjustable blade thickness. Slice, julienne, grate, shred, and dice with one tool. 5 interchangeable stainless steel blades. Safety hand guard protects fingers. Non-slip base for stable cutting. Compact design with blade storage container.',features:['5-in-1 design','Adjustable thickness','SS blades','Safety guard','Non-slip base'],specs:{'Brand':'YourMart','Type':'Mandoline Slicer','Functions':'5','Blades':'5 SS interchangeable','Safety':'Hand guard included','Thickness':'Adjustable'}}),
  P(205,'Silicone Kitchen Utensils Set 6-Piece Heat Resistant','YourMart','kitchen',949,1200,4.7,42,18,'1556909114-f6e7ad7d3136',{featured:true,description:'Premium 6-piece silicone kitchen utensil set. Includes spatula, spoon, ladle, tongs, whisk, and brush. Heat resistant up to 230°C for cooking safety. Non-stick friendly — won\'t scratch pans. Food-grade silicone with wooden handles. Dishwasher safe for easy cleaning. Beautiful set perfect for new kitchen.',features:['6-piece set','230°C heat resistant','Non-stick safe','Wooden handles','Dishwasher safe'],specs:{'Brand':'YourMart','Type':'Utensil Set','Pieces':'6','Material':'Silicone + Wood','Heat':'Up to 230°C','Safety':'Food-grade BPA-free'}}),
  P(206,'Electric Kettle Mini 0.8L Travel Fast Boil 600W','YourMart','kitchen',1299,1500,4.3,35,22,'1556909114-f6e7ad7d3136',{description:'Compact 0.8L mini electric kettle for travel and office. 600W fast boil — water ready in 3 minutes. Stainless steel interior with cool-touch exterior. Auto shut-off and boil-dry protection. Folding handle and dual voltage for travel. Perfect for hotel rooms, hostel, and dorm use.',features:['0.8L compact','3-min fast boil','Auto shut-off','Cool-touch body','Travel friendly'],specs:{'Brand':'YourMart','Type':'Electric Kettle','Capacity':'0.8L','Power':'600W','Material':'Stainless Steel','Safety':'Auto shut-off + boil-dry'}}),
  P(207,'Egg Bite Mold Silicone 7-Cup Instant Pot Compatible','YourMart','kitchen',399,500,4.5,48,60,'1556909114-f6e7ad7d3136',{trending:true,description:'Silicone egg bite mold with 7 cups for Instant Pot and steamer. Food-grade flexible silicone for easy pop-out release. Make perfect egg bites, muffins, and frozen treats. Lid included for storage and steaming. Dishwasher, oven, and freezer safe. Each cup holds approximately 70ml.',features:['7-cup mold','Flexible silicone','Lid included','Dishwasher safe','Multi-use'],specs:{'Brand':'YourMart','Type':'Egg Mold','Cups':'7','Material':'Food-grade silicone','Capacity':'70ml each','Compatibility':'Instant Pot / Steamer'}}),

  // ---- Kids & Toys (Markaz) ----
  P(208,'Magnetic Tiles Building Set 42 Pieces STEM Learning','Markaz','kids-babies',1499,1800,4.7,88,25,'1515488042361-ee00e0ddd4e4',{trending:true,featured:true,description:'42-piece magnetic tiles building set for STEM learning and creative play. Strong magnets for stable construction of castles, houses, and shapes. Translucent colored tiles catch light beautifully. Develops spatial awareness, creativity, and fine motor skills. Compatible with other magnetic tile brands. Safe rounded edges for kids 3+.',features:['42 magnetic tiles','STEM learning','Strong magnets','Translucent colors','Age 3+ safe'],specs:{'Brand':'Markaz','Type':'Magnetic Tiles','Pieces':'42','Material':'ABS + Magnet','Age':'3+','Shapes':'Triangles + Squares'}}),
  P(209,'Dinosaur Figure Set 12 Pieces Realistic Action Toys','Markaz','kids-babies',449,550,4.4,72,50,'1515488042361-ee00e0ddd4e4',{bestSeller:true,description:'Set of 12 realistic dinosaur figure toys for kids. Includes T-Rex, Stegosaurus, Triceratops, Brachiosaurus, and more. Hand-painted with realistic colors and textures. Durable non-toxic PVC material safe for children. Perfect for educational play, diorama, and birthday gifts. Size range 10-18cm per dinosaur.',features:['12 dinosaurs','Hand-painted','Non-toxic PVC','Educational play','10-18cm size'],specs:{'Brand':'Markaz','Type':'Dinosaur Set','Pieces':'12','Material':'Non-toxic PVC','Paint':'Hand-painted','Size':'10-18cm each'}}),
  P(210,'Kids Water Gun Super Soaker 800ml Capacity','Markaz','kids-babies',399,500,4.3,65,55,'1515488042361-ee00e0ddd4e4',{trending:true,description:'Super soaker water gun with 800ml large capacity tank. Shoots water up to 10 meters for ultimate water fights. Easy pump action for continuous fire. Lightweight design suitable for kids age 5+. Durable ABS plastic for summer outdoor fun. Bright blue and orange color for visibility.',features:['800ml tank','10m range','Pump action','Age 5+','ABS durable'],specs:{'Brand':'Markaz','Type':'Water Gun','Capacity':'800ml','Range':'10 meters','Action':'Pump','Material':'ABS Plastic'}}),
  P(211,'Kids Walkie Talkie Set 2-Pack 2-Way Radio 3KM Range','Markaz','kids-babies',849,1000,4.5,42,28,'1515488042361-ee00e0ddd4e4',{isNew:true,description:'Kids walkie talkie set with 2-way radio communication. 3KM range for outdoor adventures and neighborhood play. 22 channels with auto scan. Built-in flashlight and LCD display. VOX hands-free mode for easy use. Durable drop-resistant design. Perfect for camping, hiking, and hide-and-seek.',features:['3KM range','22 channels','Built-in flashlight','VOX hands-free','Drop-resistant'],specs:{'Brand':'Markaz','Type':'Walkie Talkie','Set':'2 pack','Range':'3KM','Channels':'22','Power':'4× AAA each'}}),
  P(212,'Slime Making Kit 12 Colors Glow-in-Dark Accessories','Markaz','kids-babies',499,650,4.6,55,40,'1515488042361-ee00e0ddd4e4',{trending:true,description:'Complete slime making kit with 12 vibrant colors including glow-in-dark. Includes foam balls, glitter, and fruit slices for mixing. Non-toxic borax-free formula safe for kids. Create fluffy, crunchy, and butter slime. Storage containers included for keeping slime fresh. Step-by-step instruction guide for beginners.',features:['12 colors + glow','Mix-ins included','Borax-free safe','Multiple slime types','Storage containers'],specs:{'Brand':'Markaz','Type':'Slime Kit','Colors':'12','Safety':'Non-toxic borax-free','Includes':'Foam balls + glitter + fruit','Age':'6+'}}),

  // ---- Men's Essentials (YourMart) ----
  P(213,'Men Wallet RFID Blocking Genuine Leather Brown','YourMart','mens-fashion',599,750,4.5,82,35,'1483985988355-763728e1935b',{bestSeller:true,description:'Genuine leather men wallet with RFID blocking technology. Protects credit cards from electronic pickpocketing. 8 card slots, 2 bill compartments, and 1 ID window. Slim bifold design fits comfortably in pocket. Premium stitching for long-lasting durability. Classic brown color for professional and casual style.',features:['RFID blocking','Genuine leather','8 card slots','Slim bifold','Premium stitching'],specs:{'Brand':'YourMart','Type':'Men Wallet','Material':'Genuine Leather','Card Slots':'8','RFID':'Yes','Color':'Brown'}}),
  P(214,'Men Belt Automatic Buckle Genuine Leather Black','YourMart','mens-fashion',549,700,4.4,68,40,'1483985988355-763728e1935b',{trending:true,description:'Automatic buckle genuine leather belt for men in black. No-holes design with micro-adjustment for perfect fit. 35mm width suitable for formal and casual wear. Smooth ratchet mechanism for easy on/off. Genuine cowhide leather that improves with age. Trim to fit — cut end for exact waist size.',features:['Auto buckle','No holes design','Micro-adjustment','Genuine cowhide','Trim to fit'],specs:{'Brand':'YourMart','Type':'Belt','Material':'Genuine Leather','Width':'35mm','Buckle':'Automatic ratchet','Color':'Black'}}),
  P(215,'Men Track Suit 2-Piece Zip-Up Breathable Polyester','YourMart','mens-fashion',1299,1500,4.3,45,22,'1483985988355-763728e1935b',{description:'2-piece men track suit with zip-up jacket and jogger pants. Breathable polyester mesh lining for comfort. Side pockets on both jacket and pants. Elastic waistband with drawstring for adjustable fit. Ribbed cuffs for clean look. Perfect for gym, jogging, and casual outings.',features:['2-piece set','Breathable mesh','Zip-up jacket','Elastic waistband','Ribbed cuffs'],specs:{'Brand':'YourMart','Type':'Track Suit','Pieces':'2','Material':'Polyester','Lining':'Mesh','Fit':'Regular'}}),
  P(216,'Men Digital Sports Watch Waterproof LED Backlight','YourMart','watches-bags',499,650,4.4,92,50,'1523275335684-37898b6baf30',{trending:true,bestSeller:true,description:'Digital sports watch for men with LED backlight and waterproof design. 50M water resistance for swimming and showering. Dual time zone display for travelers. Alarm, stopwatch, and date functions. Adjustable resin strap fits most wrist sizes. Lightweight at just 40g for all-day comfort.',features:['50M waterproof','LED backlight','Dual timezone','Alarm + stopwatch','40g lightweight'],specs:{'Brand':'YourMart','Type':'Sports Watch','Display':'Digital','Water Resistance':'50M','Functions':'Alarm/Stopwatch/Date','Weight':'40g'}}),

  // ---- Women's Fashion & Beauty (Markaz) ----
  P(217,'Embroidered Khussas Flat Shoes Traditional Handwork','Markaz','womens-shoes',749,950,4.6,58,28,'1543163521-1bf539c55dd2',{trending:true,description:'Traditional embroidered khussas with handcrafted threadwork. Genuine leather sole for lasting comfort and durability. Intricate multi-color embroidery with mirror accents. Flat sole ideal for daily wear and festive occasions. Soft padded insole for all-day comfort. Available in sizes 36-42.',features:['Handcrafted','Leather sole','Mirror accents','Padded insole','Sizes 36-42'],specs:{'Brand':'Markaz','Type':'Khussas','Sole':'Leather','Embroidery':'Hand-made','Insole':'Padded','Sizes':'36-42'}}),
  P(218,'Chiffon Dupatta Digital Print 2.5m Party Wear','Markaz','womens-fashion',549,700,4.5,75,40,'1595771055363-048d76554a2f',{bestSeller:true,description:'Premium chiffon dupatta with vibrant digital print. 2.5m length for elegant draping styles. Lightweight and breathable fabric for all seasons. Beautiful floral print in rich colors. Finished edges with delicate border. Perfect for parties, weddings, and formal events.',features:['2.5m length','Digital print','Lightweight chiffon','Floral design','Finished edges'],specs:{'Brand':'Markaz','Type':'Dupatta','Fabric':'Chiffon','Length':'2.5m','Print':'Digital floral','Use':'Party/Formal'}}),
  P(219,'Hair Accessories Set 20 Pieces Clips Pins Bands','Markaz','beauty',349,450,4.4,105,60,'1596462502278-27bfdc403348',{trending:true,bestSeller:true,description:'Complete hair accessories set with 20 pieces in one pack. Includes bobby pins, claw clips, hair ties, headband, and scrunchies. Assorted colors to match any outfit. Strong grip that holds hair all day. Gentle on hair — no pulling or breakage. Compact storage pouch included.',features:['20-piece set','Assorted colors','Strong grip','Gentle on hair','Storage pouch'],specs:{'Brand':'Markaz','Type':'Hair Accessories','Pieces':'20','Includes':'Pins/Clips/Ties/Headband/Scrunchies','Colors':'Assorted','Pouch':'Included'}}),
  P(220,'Women Clutch Bag Embroidered Evening Party','Markaz','watches-bags',699,850,4.5,42,25,'1523275335684-37898b6baf30',{description:'Elegant embroidered clutch bag for evening parties and weddings. Hand-embroidered floral design with sequin accents. Metal frame with clasp closure for security. Removable chain strap for shoulder or handheld use. Interior pocket for cards and essentials. Perfect size for phone, lipstick, and keys.',features:['Hand embroidered','Sequin accents','Clasp closure','Chain strap','Interior pocket'],specs:{'Brand':'Markaz','Type':'Clutch Bag','Closure':'Metal clasp','Strap':'Removable chain','Design':'Embroidered + Sequins','Size':'22×13×6cm'}}),

  // ---- Home & Decor (YourMart) ----
  P(221,'Himalayan Salt Lamp Natural 2-3kg Wooden Base','YourMart','home-lifestyle',999,1200,4.7,88,20,'1556228453-efd6c1ff04f6',{trending:true,featured:true,description:'Natural Himalayan salt lamp with wooden base. 2-3kg hand-mined crystal from Khewra salt mines, Pakistan. Emits warm amber glow for calming ambiance. Air-purifying properties — attracts water molecules from air. Dimmable touch switch for brightness control. Beautiful natural shape — each piece is unique. Perfect for bedroom, living room, and meditation space.',features:['Khewra salt mine','2-3kg natural','Air purifying','Dimmable touch','Unique shape'],specs:{'Brand':'YourMart','Type':'Salt Lamp','Weight':'2-3kg','Source':'Khewra Mines','Base':'Wooden','Control':'Touch dimmer'}}),
  P(222,'Wall Sticker Decal Islamic Calligraphy Bismillah Gold','YourMart','islamic',349,450,4.6,72,45,'1542816417-0983c9c9ad53',{bestSeller:true,description:'Islamic calligraphy wall sticker decal in gold — Bismillah design. Premium vinyl with metallic gold finish. Easy peel-and-stick application on any smooth surface. Removable without damaging walls. 60×40cm size perfect for entrance and living room. Waterproof and fade-resistant for long-lasting beauty.',features:['Gold metallic finish','Peel and stick','Removable','60×40cm','Waterproof vinyl'],specs:{'Brand':'YourMart','Type':'Wall Decal','Design':'Bismillah Calligraphy','Size':'60×40cm','Material':'Premium Vinyl','Color':'Metallic Gold'}}),
  P(223,'LED Strip Light 5M RGB Remote Control USB Powered','YourMart','home-lifestyle',499,650,4.5,95,55,'1556228453-efd6c1ff04f6',{trending:true,bestSeller:true,description:'5-meter RGB LED strip light with 44-key remote control. 16 colors and 4 dynamic modes — flash, strobe, fade, and smooth. USB powered — plug into TV, PC, or power bank. Self-adhesive backing for easy installation. Cuttable every 3 LEDs for custom length. Perfect for room decoration, TV backlight, and desk accent.',features:['5M length','16 colors','4 dynamic modes','USB powered','Self-adhesive'],specs:{'Brand':'YourMart','Type':'LED Strip','Length':'5m','Colors':'16 + modes','Power':'USB 5V','Control':'44-key remote','Cuttable':'Every 3 LEDs'}}),
  P(224,'Laundry Basket Foldable Large Capacity 72L Gray','YourMart','home-lifestyle',699,850,4.3,38,30,'1556228453-efd6c1ff04f6',{description:'Large capacity 72L foldable laundry basket in gray. Durable Oxford fabric with PE coating for water resistance. Collapsible design saves space when not in use. Two reinforced handles for easy carrying. Mesh top keeps clothes breathable. Also perfect for toy storage and general organization.',features:['72L capacity','Oxford fabric','Foldable design','PE waterproof coating','Reinforced handles'],specs:{'Brand':'YourMart','Type':'Laundry Basket','Capacity':'72L','Material':'Oxford + PE','Foldable':'Yes','Color':'Gray','Handles':'2 reinforced'}}),

  // ---- Sports & Fitness (YourMart) ----
  P(225,'Resistance Band Set 5 Levels Latex Exercise Loop','YourMart','sports-fitness',399,500,4.5,78,50,'1517836357463-d25dfeac3438',{trending:true,bestSeller:true,description:'Set of 5 resistance bands in different strength levels. Made from premium natural latex for durability and elasticity. Color-coded from light (5lb) to extra heavy (30lb). Use for yoga, pilates, physical therapy, and home workouts. Lightweight and portable — fits in pocket or bag. Includes carry bag and exercise guide.',features:['5 resistance levels','Natural latex','Color-coded','Portable','Carry bag included'],specs:{'Brand':'YourMart','Type':'Resistance Bands','Levels':'5','Material':'Natural Latex','Range':'5-30 lbs','Includes':'Carry bag + guide'}}),
  P(226,'Jump Rope Speed Training Adjustable Steel Wire','YourMart','sports-fitness',299,400,4.4,65,60,'1517836357463-d25dfeac3438',{bestSeller:true,description:'Professional speed jump rope with steel wire cable. Adjustable length from 2.1m to 3m for any height. Ball bearing system for smooth, tangle-free rotation. Foam handles for comfortable non-slip grip. Great for cardio, boxing training, and weight loss. Compact and lightweight for gym or outdoor use.',features:['Steel wire cable','Adjustable length','Ball bearing system','Foam handles','Tangle-free'],specs:{'Brand':'YourMart','Type':'Jump Rope','Cable':'Steel wire','Length':'2.1-3m adjustable','Handles':'Foam non-slip','Bearing':'Ball bearing'}}),
  P(227,'Waist Trimmer Belt Sweat Sauna Neoprene','YourMart','sports-fitness',449,550,4.3,55,45,'1517836357463-d25dfeac3438',{trending:true,description:'Neoprene waist trimmer belt for enhanced sweat during workouts. Increases core temperature for sauna-like effect. Contoured design for comfortable fit during exercise. Anti-slip inner lining stays in place. Adjustable Velcro closure fits waist 60-110cm. Supports lower back during heavy lifting.',features:['Neoprene material','Sauna effect','Anti-slip lining','Velcro adjustable','Back support'],specs:{'Brand':'YourMart','Type':'Waist Trimmer','Material':'Neoprene','Waist':'60-110cm','Closure':'Velcro','Effect':'Enhanced sweating'}}),

  // ---- Auto & Car (Markaz) ----
  P(228,'Car Air Freshener Vent Clip 3-Pack Long Lasting','Markaz','car-accessories',299,400,4.4,82,65,'1503376780353-7e6692767b70',{bestSeller:true,description:'Pack of 3 car air freshener vent clips in different scents. Ocean, lemon, and lavender fragrances included. Long-lasting scent for up to 30 days per clip. Easy clip-on design fits any car air vent. Rotating clip for vertical and horizontal vents. Compact design doesn\'t block airflow.',features:['3-pack set','30-day lasting','3 scents','Clip-on design','Fits all vents'],specs:{'Brand':'Markaz','Type':'Air Freshener','Quantity':'3 clips','Scents':'Ocean/Lemon/Lavender','Duration':'30 days each','Mount':'Vent clip'}}),
  P(229,'Car Mobile Holder Suction Cup Dashboard Windshield','Markaz','car-accessories',549,700,4.5,48,35,'1503376780353-7e6692767b70',{trending:true,description:'Universal car phone holder with suction cup for dashboard and windshield. 360° rotation for optimal viewing angle. One-touch quick release for easy phone mounting. Adjustable arms fit phones 4-7 inches. Powerful suction cup stays firm on bumpy roads. Also works as desk stand when removed from car.',features:['Suction cup mount','360° rotation','One-touch release','4-7 inch phones','Dashboard + windshield'],specs:{'Brand':'Markaz','Type':'Phone Holder','Mount':'Suction cup','Rotation':'360°','Phone Size':'4-7 inch','Use':'Dashboard/Windshield/Desk'}}),
  P(230,'Tire Pressure Gauge Digital LCD 150PSI Backlit','Markaz','car-accessories',449,550,4.3,35,40,'1503376780353-7e6692767b70',{description:'Digital tire pressure gauge with LCD backlight display. Measures 0-150 PSI with 0.1 PSI accuracy. Backlit LCD for easy reading in dark. Nozzle fits all standard tire valves. Also measures bike, motorcycle, and sports ball pressure. Auto shut-off saves battery. Ergonomic grip for comfortable use.',features:['LCD backlight','0-150 PSI','0.1 accuracy','Auto shut-off','Multi-use'],specs:{'Brand':'Markaz','Type':'Tire Gauge','Range':'0-150 PSI','Accuracy':'0.1 PSI','Display':'LCD backlit','Battery':'2× AAA included'}}),

  // ---- Islamic Products (Markaz) ----
  P(231,'Tasbeeh Counter Digital Finger Ring Wristband','Markaz','islamic',399,500,4.6,95,50,'1542816417-0983c9c9ad53',{trending:true,bestSeller:true,description:'Digital tasbeeh counter in wristband form for easy dhikr. Counts up to 99,999 with one-button reset. Clear LCD display shows count at a glance. Comfortable silicone band for all-day wear. Water-resistant for daily use including wudu. Lightweight at just 25g. Perfect for daily zikr, tahajjud, and Ramadan.',features:['99,999 count','LCD display','Silicone band','Water-resistant','25g lightweight'],specs:{'Brand':'Markaz','Type':'Digital Tasbeeh','Count':'Up to 99,999','Display':'LCD','Material':'Silicone','Weight':'25g','Battery':'LR1130 included'}}),
  P(232,'Prayer Beads Tasbeeh 33 Count Premium Wood','Markaz','islamic',349,450,4.5,68,55,'1542816417-0983c9c9ad53',{bestSeller:true,description:'Premium wooden prayer beads tasbeeh for daily dhikr. 33 beads with separator markers at every 11. Handcrafted from natural Turkish wood. Smooth polished surface comfortable for extended use. Compact size fits in pocket or purse. Beautiful natural wood grain — each piece unique.',features:['33 bead count','Natural wood','Handcrafted','Smooth polished','Pocket size'],specs:{'Brand':'Markaz','Type':'Tasbeeh','Beads':'33','Material':'Natural wood','Craft':'Handmade','Length':'25cm'}}),
  P(233,'Islamic Wall Clock Adhan Alarm 6 Prayer Times LED','Markaz','islamic',1299,1500,4.4,42,18,'1542816417-0983c9c9ad53',{description:'Islamic wall clock with automatic Adhan alarm for 6 prayer times. Large LED display with Hijri and Gregorian date. Pre-programmed for 500+ cities worldwide. Volume control for Adhan alarm. Qibla direction indicator. Temperature and humidity display. Battery backup maintains settings during power outage.',features:['Auto Adhan alarm','500+ cities','Hijri + Gregorian','Qibla indicator','LED display'],specs:{'Brand':'Markaz','Type':'Islamic Clock','Display':'LED','Cities':'500+','Calendar':'Hijri + Gregorian','Power':'AC + AA backup','Features':'Temp/Humidity/Qibla'}}),

  // ---- Pet & Animal (Markaz) ----
  P(234,'Dog Toy Rope Tug-of-War Large Breed Indestructible','Markaz','pet-care',399,500,4.5,48,40,'1587300003388-59208cc962cb',{trending:true,description:'Indestructible rope tug toy for large breed dogs. 50cm length with multiple knots for chewing. Natural cotton rope — safe if accidentally ingested in small amounts. Cleans teeth and massages gums during play. Perfect for tug-of-war and fetch. Recommended for dogs 15kg and above.',features:['50cm length','Natural cotton','Teeth cleaning','Large breeds','Multi-knot design'],specs:{'Brand':'Markaz','Type':'Dog Rope Toy','Length':'50cm','Material':'Natural cotton','Knots':'Multiple','Dog Size':'15kg+'}}),
  P(235,'Fish Tank Aquarium LED Light Clip-On 7W','Markaz','pet-care',599,750,4.3,32,25,'1587300003388-59208cc962cb',{description:'Clip-on LED aquarium light for fish tanks up to 60cm. 7W full spectrum for healthy plant growth. Adjustable gooseneck for directional lighting. White + blue + red LEDs for day and night modes. Low heat output safe for fish. Easy clip mount on any tank rim up to 12mm thick.',features:['7W full spectrum','Clip-on mount','Adjustable gooseneck','3 color modes','Low heat'],specs:{'Brand':'Markaz','Type':'Aquarium Light','Power':'7W','Tank Size':'Up to 60cm','LEDs':'White+Blue+Red','Mount':'Clip-on 12mm rim'}}),

  // ---- More Trending Markaz ----
  P(236,'Portable Juice Blender USB 6 Blades 400ml','Markaz','kitchen',1199,1400,4.6,82,25,'1556909114-f6e7ad7d3136',{trending:true,bestSeller:true,description:'Portable USB rechargeable juice blender with 6 blades. 400ml BPA-free Tritan bottle. Blend smoothies, protein shakes, and baby food anywhere. 6 stainless steel blades for smooth results in 30 seconds. One-touch operation — double-click to start. Charge once for 15+ blends. Perfect for gym, office, and travel.',features:['6-blade system','400ml capacity','USB rechargeable','BPA-free Tritan','30-sec blending'],specs:{'Brand':'Markaz','Type':'Portable Blender','Capacity':'400ml','Blades':'6 SS','Battery':'2000mAh','Charge':'USB-C','Blends':'15+ per charge'}}),
  P(237,'Sticky Note Set 8 Colors 500 Sheets Desk Organizer','Markaz','stationery',275,350,4.5,88,75,'1507925921958-8a62f3d1a50d',{bestSeller:true,description:'Sticky note set with 8 vibrant colors and 500 total sheets. 76×76mm standard size for notes and reminders. Strong adhesive that sticks firmly and removes cleanly. Bright neon colors for high visibility. Compact dispenser box keeps notes organized. Perfect for office, school, and home study.',features:['8 colors','500 sheets','76×76mm size','Strong adhesive','Dispenser box'],specs:{'Brand':'Markaz','Type':'Sticky Notes','Colors':'8','Sheets':'500 total','Size':'76×76mm','Adhesive':'Strong removable'}}),
  P(238,'Highlighter Pen Set 6 Colors Chisel Tip','Markaz','stationery',249,350,4.4,72,80,'1507925921958-8a62f3d1a50d',{trending:true,description:'Set of 6 highlighter pens with chisel tip in vibrant colors. Yellow, pink, orange, green, blue, and purple. Chisel tip for broad and fine highlighting. Quick-drying ink prevents smudging on paper. Translucent barrel shows ink level. Comfortable grip for extended study sessions.',features:['6 colors','Chisel tip','Quick-drying','Smudge-proof','Translucent barrel'],specs:{'Brand':'Markaz','Type':'Highlighter Set','Colors':'6','Tip':'Chisel (broad/fine)','Ink':'Quick-dry','Body':'Translucent'}}),
  P(239,'Bedside Caddy Organizer 5 Pockets Felt Hanging','Markaz','bedding',449,550,4.5,58,35,'1555041469-a586c61ea9bc',{trending:true,description:'Felt bedside caddy organizer with 5 pockets for neat storage. Hangs between mattress and bed frame securely. Store phone, glasses, remote, books, and water bottle. Premium thick felt material for durability. No tools needed — just slide under mattress. Fits single, double, and king beds.',features:['5 pockets','Premium felt','No tools install','Under-mattress hold','All bed sizes'],specs:{'Brand':'Markaz','Type':'Bed Caddy','Material':'Thick felt','Pockets':'5','Installation':'Slide under mattress','Compatibility':'All bed sizes'}}),
  P(240,'Silk Pillowcase Queen Size Hair Care Anti-Wrinkle','Markaz','bedding',899,1100,4.6,45,20,'1555041469-a586c61ea9bc',{featured:true,description:'Pure silk pillowcase for hair care and anti-wrinkle benefits. Queen size 50×75cm with hidden zipper. Reduces hair breakage and frizz while sleeping. Smooth surface prevents sleep creases on skin. Temperature-regulating for cool summers and warm winters. Machine washable on gentle cycle. Available in champagne, pink, and silver.',features:['Pure silk','Anti-wrinkle','Hair care','Hidden zipper','Machine washable'],specs:{'Brand':'Markaz','Type':'Silk Pillowcase','Size':'50×75cm Queen','Material':'Pure silk','Closure':'Hidden zipper','Care':'Machine wash gentle'}}),
  P(241,'Ear Wax Removal Tool 6-Piece Stainless Steel Set','Markaz','beauty',299,400,4.3,55,50,'1596462502278-27bfdc403348',{trending:true,description:'Professional ear wax removal tool set with 6 stainless steel instruments. Different tip shapes for various ear care needs. Medical-grade stainless steel — sterilizable and rust-proof. Rounded tips for safe and comfortable use. Comes in leather carrying case. Easy to clean with alcohol or boiling water.',features:['6-piece set','Medical-grade SS','Rounded safe tips','Leather case','Sterilizable'],specs:{'Brand':'Markaz','Type':'Ear Care Set','Pieces':'6','Material':'Stainless Steel','Safety':'Rounded tips','Case':'Leather pouch'}}),
  P(242,'Rechargeable Electric Lighter Arc Dual USB Windproof','YourMart','home-lifestyle',549,700,4.5,82,35,'1556228453-efd6c1ff04f6',{trending:true,description:'Rechargeable arc electric lighter with dual USB ports. Plasma arc technology works in wind and rain. No flame, no gas — USB rechargeable 300+ uses per charge. Dual arc for faster lighting. LED battery indicator shows charge level. Safety switch prevents accidental activation. Perfect for candles, kitchen, and camping.',features:['Plasma arc','Windproof','USB rechargeable','Dual arc','LED indicator'],specs:{'Brand':'YourMart','Type':'Electric Lighter','Technology':'Plasma Arc','Charge':'USB','Uses':'300+ per charge','Safety':'Child lock switch'}}),
  P(243,'Mini Desktop Vacuum Cleaner Battery Operated','YourMart','home-lifestyle',449,550,4.4,68,45,'1556228453-efd6c1ff04f6',{bestSeller:true,description:'Cute mini desktop vacuum cleaner for cleaning keyboard and desk. Battery operated — 2× AA batteries (not included). Strong suction picks up crumbs, dust, and eraser shavings. Compact penguin design adds fun to desk. One-touch empty — twist to open and dump. Perfect for office desk, keyboard, and craft table cleanup.',features:['Battery operated','Strong suction','Penguin design','One-touch empty','Keyboard cleaning'],specs:{'Brand':'YourMart','Type':'Desk Vacuum','Power':'2× AA batteries','Suction':'Strong','Design':'Penguin','Use':'Desk/keyboard/craft'}}),
  P(244,'Bluetooth Sleep Mask Headphones Wireless 3D Contour','YourMart','beauty',899,1100,4.5,42,20,'1596462502278-27bfdc403348',{isNew:true,trending:true,description:'3D contour sleep mask with built-in Bluetooth headphones. Ultra-soft memory foam for zero pressure on eyes. Wireless headphones for music, audiobooks, and white noise. 10-hour battery for full night of sleep. Adjustable speakers position perfectly over ears. Blocks 100% light for deep sleep. Perfect for travel, shift workers, and light sleepers.',features:['3D memory foam','Bluetooth 5.2','10-hour battery','Zero eye pressure','100% light block'],specs:{'Brand':'YourMart','Type':'Sleep Mask','Bluetooth':'5.2','Battery':'10 hours','Foam':'Memory foam','Speakers':'Adjustable thin'}}),
  P(245,'Collapsible Laundry Hamper 2-Pack 80L Each Handles','YourMart','home-lifestyle',599,750,4.3,48,35,'1556228453-efd6c1ff04f6',{description:'Set of 2 collapsible laundry hampers with 80L capacity each. Durable polyester fabric with PE board support. Two reinforced handles for easy carrying. Folds flat when not in use to save space. Mesh top panel keeps clothes breathable. Available in gray and beige. Also great for toy storage and organizing.',features:['2-pack set','80L each','Collapsible design','Reinforced handles','Mesh top panel'],specs:{'Brand':'YourMart','Type':'Laundry Hamper','Quantity':'2','Capacity':'80L each','Material':'Polyester + PE','Foldable':'Yes'}}),
"""

# Insert before the closing bracket of PRODUCTS array
content = content.replace(
    "\n];\n\n// Build related ids by same category",
    new_products + "\n];\n\n// Build related ids by same category"
)

print(f"✅ Added 53 new unique trending low-cost products (IDs 193-245)")

# ════════════════════════════════════════════════════════════════
# SAVE
# ════════════════════════════════════════════════════════════════

with open('src/lib/data.ts', 'w') as f:
    f.write(content)

# Verify
with open('src/lib/data.ts') as f:
    verify = f.read()
pcount = len(re.findall(r"P\(\d+,", verify))
print(f"\n🎉 TOTAL PRODUCTS: {pcount}")
print(f"   sfile.chatglm remaining: {verify.count('sfile.chatglm')}")
